import { useEffect, useState } from "react";
import { api } from "../../lib/api";
import { RESELLER_URL } from "../../lib/portal";

type Reseller={id:string;name:string;slug:string;status:string;customers:number;vehicles:number;wholesalePence:number;supportEmail:string|null;wholesaleModel:string};
type Customer={id:string;name:string;slug:string;subscriptionPlan:string;subscriptionStatus:string;vehicleLimit:number;vehicleUsage:number;wholesaleMonthlyPence:number|null;retailMonthlyPence:number|null};
const money=(p:number|null|undefined)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format((p??0)/100);

export function ManagerResellersPage(){
  const [rows,setRows]=useState<Reseller[]>([]);const [selected,setSelected]=useState("");const [customers,setCustomers]=useState<Customer[]>([]);const [message,setMessage]=useState("");
  const [name,setName]=useState("");const [slug,setSlug]=useState("");const [email,setEmail]=useState("");const [inviteEmail,setInviteEmail]=useState("");const [inviteUrl,setInviteUrl]=useState("");
  async function load(){const next=await api<Reseller[]>("/resellers");setRows(next);if(!selected&&next[0])setSelected(next[0].id);}
  useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Could not load resellers"));},[]);
  useEffect(()=>{if(!selected){setCustomers([]);return;}void api<Customer[]>(`/resellers/${selected}/customers`).then(setCustomers).catch(e=>setMessage(e instanceof Error?e.message:"Could not load reseller customers"));},[selected]);
  async function create(e:React.FormEvent){e.preventDefault();setMessage("");try{const reseller=await api<Reseller>("/resellers",{method:"POST",body:JSON.stringify({name,slug,supportEmail:email||undefined,wholesaleModel:"PER_TENANT",branding:{name,primaryColor:"#197B58",accentColor:"#32C58B",sidebarColor:"#0E1B2C"}})});setName("");setSlug("");setEmail("");setSelected(reseller.id);setMessage("Reseller created.");await load();}catch(err){setMessage(err instanceof Error?err.message:"Could not create reseller");}}
  async function invite(e:React.FormEvent){e.preventDefault();if(!selected)return;setInviteUrl("");try{const result=await api<{inviteUrl:string}>(`/resellers/${selected}/invites`,{method:"POST",body:JSON.stringify({email:inviteEmail||undefined,role:"ADMIN",expiresInDays:7})});const token=new URL(result.inviteUrl).searchParams.get("token");setInviteUrl(token?`${RESELLER_URL}?token=${encodeURIComponent(token)}`:result.inviteUrl);setMessage("One-time reseller administrator invitation created.");}catch(err){setMessage(err instanceof Error?err.message:"Could not create invitation");}}
  const current=rows.find(r=>r.id===selected);
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Manager · Resellers</p><h1>Reseller control</h1><p className="subtle">Create channels, appoint their administrator and see only the commercial portfolio assigned to them.</p></div></div>{message&&<p className="form-message">{message}</p>}
    <div className="metric-grid"><article className="metric-card"><div><p>Resellers</p><strong>{rows.length}</strong></div></article><article className="metric-card"><div><p>Reseller customers</p><strong>{rows.reduce((n,r)=>n+r.customers,0)}</strong></div></article><article className="metric-card"><div><p>Wholesale MRR</p><strong>{money(rows.reduce((n,r)=>n+r.wholesalePence,0))}</strong></div></article></div>
    <section className="panel" style={{marginTop:20,padding:18}}><h2>Create reseller</h2><form onSubmit={create} className="form-grid"><label>Trading name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))}/></label><label>Support email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><div><button className="primary-button" type="submit">Create reseller</button></div></form></section>
    <section className="panel" style={{marginTop:20,padding:18}}><h2>Manage channel</h2>{!rows.length?<p>No resellers yet.</p>:<><label>Reseller<select value={selected} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{current&&<div className="metric-grid" style={{marginTop:16}}><article className="metric-card"><div><strong>{current.name}</strong><small style={{display:"block"}}>{current.status} · {current.wholesaleModel}</small></div></article><article className="metric-card"><div><strong>{current.customers} customers</strong><small style={{display:"block"}}>{current.vehicles} vehicles</small></div></article><article className="metric-card"><div><strong>{money(current.wholesalePence)}</strong><small style={{display:"block"}}>Wholesale monthly value</small></div></article></div>}</>}</section>
    {selected&&<section className="panel" style={{marginTop:20,padding:18}}><h2>Reseller administrator</h2><form onSubmit={invite} className="form-grid"><label>Email<input type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="admin@reseller.co.uk"/></label><div><button type="submit">Generate 7-day invite</button></div></form>{inviteUrl&&<div style={{marginTop:14}}><strong>One-time URL</strong><p style={{wordBreak:"break-all"}}>{inviteUrl}</p><button className="secondary-button" onClick={()=>void navigator.clipboard.writeText(inviteUrl)}>Copy link</button></div>}</section>}
    {selected&&<section className="panel" style={{marginTop:20,padding:18}}><h2>{current?.name??"Reseller"} customers</h2>{!customers.length?<p>No customer companies linked yet.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr><th align="left">Company</th><th align="left">Status</th><th align="right">Vehicles</th><th align="right">Wholesale</th><th align="right">Retail</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><strong>{c.name}</strong><br/><small>{c.slug}</small></td><td>{c.subscriptionPlan} · {c.subscriptionStatus}</td><td align="right">{c.vehicleUsage}/{c.vehicleLimit}</td><td align="right">{money(c.wholesaleMonthlyPence)}</td><td align="right">{money(c.retailMonthlyPence)}</td></tr>)}</tbody></table></div>}</section>}
  </section>;
}