import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Building2, CircleDollarSign, ReceiptText, Store, Users } from "lucide-react";
import { api } from "../../lib/api";

type Portfolio={companyId:string;companyName:string;slug:string;subscriptionPlan:string;subscriptionStatus:string;trialEndsAt:string|null;trialDaysRemaining:number|null;trialExpired:boolean;readOnly:boolean;vehicleLimit:number;vehicleUsage:number;members:number;commitmentMonths:number;commitmentStartedAt:string|null;commitmentEndsAt:string|null;resellerId:string|null;wholesaleMonthlyPence:number|null;retailMonthlyPence:number|null};
type Reseller={id:string;name:string;status:string;customers:number;vehicles:number;wholesalePence:number};
const money=(p:number|null|undefined)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format((p??0)/100);

function useOwnerData(){const[portfolio,setPortfolio]=useState<Portfolio[]>([]);const[resellers,setResellers]=useState<Reseller[]>([]);const[error,setError]=useState("");async function load(){try{const[companies,agents]=await Promise.all([api<Portfolio[]>("/commercial/portfolio"),api<Reseller[]>("/resellers")]);setPortfolio(companies);setResellers(agents);setError("");}catch(err){setError(err instanceof Error?err.message:"Unable to load manager dashboard");}}useEffect(()=>{void load();},[]);const totals=useMemo(()=>({active:portfolio.filter(c=>c.subscriptionStatus==="ACTIVE").length,trials:portfolio.filter(c=>c.subscriptionStatus==="TRIAL").length,issues:portfolio.filter(c=>c.readOnly).length,vehicles:portfolio.reduce((n,c)=>n+c.vehicleUsage,0),wholesale:portfolio.reduce((n,c)=>n+(c.wholesaleMonthlyPence??0),0),retail:portfolio.reduce((n,c)=>n+(c.retailMonthlyPence??0),0)}),[portfolio]);return{portfolio,resellers,error,totals,reload:load};}

export function PlatformControlPage(){const{portfolio,resellers,error,totals}=useOwnerData();const links=[{label:"Customers",description:`${portfolio.length} companies · ${totals.vehicles} vehicles`,to:"/customers",Icon:Building2},{label:"Resellers",description:`${resellers.length} reseller channels`,to:"/resellers",Icon:Store},{label:"Money",description:`${money(totals.wholesale)} wholesale MRR recorded`,to:"/money",Icon:CircleDollarSign}] as const;return <section className="page"><div className="page-heading"><div><p className="eyebrow">Owner-only portal</p><h1>FleetOS Manager</h1><p className="subtle">Master commercial control for customers and reseller channels. This portal is separate from every customer and white-label workspace.</p></div></div>{error&&<p className="form-message error">{error}</p>}<div className="metric-grid">{links.map(({label,description,to,Icon})=><Link key={label} to={to} className="metric-card" style={{textDecoration:"none",color:"inherit"}}><div className="metric-icon blue"><Icon size={21}/></div><div><strong style={{display:"block"}}>{label}</strong><small>{description}</small></div><ArrowRight size={17}/></Link>)}</div><section className="panel" style={{marginTop:24,padding:18}}><h2>At a glance</h2><div className="metric-grid"><article className="metric-card"><div><p>Customers</p><strong>{portfolio.length}</strong><small>{totals.active} active · {totals.trials} trial</small></div></article><article className="metric-card"><div><p>Need attention</p><strong>{totals.issues}</strong><small>Past due, cancelled or expired</small></div></article><article className="metric-card"><div><p>Retail MRR recorded</p><strong>{money(totals.retail)}</strong><small>Commercial records, not payment receipts</small></div></article></div></section></section>;}

export function PlatformCustomersPage(){
  const{portfolio,resellers,error,reload}=useOwnerData();const[selected,setSelected]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const current=portfolio.find(c=>c.companyId===selected)??portfolio[0];
  const[plan,setPlan]=useState("STARTER");const[status,setStatus]=useState("TRIAL");const[vehicleLimit,setVehicleLimit]=useState(5);const[resellerId,setResellerId]=useState("");const[wholesale,setWholesale]=useState("");const[retail,setRetail]=useState("");
  useEffect(()=>{if(!selected&&portfolio[0])setSelected(portfolio[0].companyId);},[portfolio,selected]);
  useEffect(()=>{if(!current)return;setPlan(current.subscriptionPlan);setStatus(current.subscriptionStatus);setVehicleLimit(current.vehicleLimit);setResellerId(current.resellerId??"");setWholesale(current.wholesaleMonthlyPence==null?"":String(current.wholesaleMonthlyPence/100));setRetail(current.retailMonthlyPence==null?"":String(current.retailMonthlyPence/100));},[current?.companyId]);
  async function save(e:React.FormEvent){e.preventDefault();if(!current)return;setBusy(true);setMessage("");try{await api(`/commercial/portfolio/${current.companyId}`,{method:"PATCH",body:JSON.stringify({subscriptionPlan:plan,subscriptionStatus:status,vehicleLimit,resellerId:resellerId||null,wholesaleMonthlyPence:wholesale===""?null:Math.round(Number(wholesale)*100),retailMonthlyPence:retail===""?null:Math.round(Number(retail)*100)})});setMessage("Customer controls saved.");await reload();}catch(err){setMessage(err instanceof Error?err.message:"Could not save customer controls");}finally{setBusy(false);}}
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Manager · Customers</p><h1>Customer control</h1><p className="subtle">Set plans, account state, fleet limits, reseller ownership and recorded commercial values without entering the customer application.</p></div></div>{error&&<p className="form-message error">{error}</p>}{message&&<p className="form-message">{message}</p>}{!portfolio.length?<div className="panel"><p>No customer companies yet.</p></div>:<div style={{display:"grid",gridTemplateColumns:"minmax(260px,.8fr) minmax(320px,1.2fr)",gap:18,alignItems:"start"}}><section className="panel" style={{padding:14}}><label>Customer<select value={selected} onChange={e=>setSelected(e.target.value)}>{portfolio.map(c=><option key={c.companyId} value={c.companyId}>{c.companyName}</option>)}</select></label><div style={{marginTop:16}}>{portfolio.map(c=><button key={c.companyId} onClick={()=>setSelected(c.companyId)} style={{display:"block",width:"100%",textAlign:"left",padding:12,marginBottom:8,borderRadius:10,border:c.companyId===current?.companyId?"2px solid var(--brand-primary)":"1px solid #dbe3ea",background:"transparent"}}><strong>{c.companyName}</strong><small style={{display:"block"}}>{c.vehicleUsage}/{c.vehicleLimit} vehicles · {c.subscriptionStatus}</small></button>)}</div></section>{current&&<form className="panel" style={{padding:18}} onSubmit={save}><h2>{current.companyName}</h2><p className="subtle">{current.slug} · {current.members} members · {current.vehicleUsage} vehicles in use</p><div className="form-grid"><label>Plan<select value={plan} onChange={e=>setPlan(e.target.value)}><option>EARLY_ACCESS</option><option>STARTER</option><option>GROWTH</option><option>ENTERPRISE</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>TRIAL</option><option>ACTIVE</option><option>PAST_DUE</option><option>CANCELLED</option></select></label><label>Vehicle limit<input type="number" min={1} value={vehicleLimit} onChange={e=>setVehicleLimit(Number(e.target.value))}/></label><label>Sales channel<select value={resellerId} onChange={e=>setResellerId(e.target.value)}><option value="">Direct FleetOS customer</option>{resellers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Wholesale £ / month<input type="number" min={0} step="0.01" value={wholesale} onChange={e=>setWholesale(e.target.value)}/></label><label>Retail £ / month<input type="number" min={0} step="0.01" value={retail} onChange={e=>setRetail(e.target.value)}/></label></div><button className="primary-button" disabled={busy}>{busy?"Saving…":"Save master controls"}</button></form>}</div>}</section>;
}

export function PlatformMoneyPage(){const{portfolio,resellers,error,totals}=useOwnerData();return <section className="page"><div className="page-heading"><div><p className="eyebrow">Manager · Money</p><h1>Commercial overview</h1><p className="subtle">Recorded subscription values across direct and reseller business. These figures are not represented as confirmed bank receipts until payment processing is connected.</p></div></div>{error&&<p className="form-message error">{error}</p>}<div className="metric-grid"><article className="metric-card"><div><p>Wholesale MRR</p><strong>{money(totals.wholesale)}</strong></div></article><article className="metric-card"><div><p>Retail MRR recorded</p><strong>{money(totals.retail)}</strong></div></article><article className="metric-card"><div><p>Paid customers</p><strong>{totals.active}</strong><small>{totals.trials} trials</small></div></article></div><section className="panel" style={{marginTop:24,padding:18}}><h2>Reseller channels</h2><div className="metric-grid">{resellers.map(r=><article className="metric-card" key={r.id}><div><strong>{r.name}</strong><small style={{display:"block"}}>{r.customers} customers · {r.vehicles} vehicles</small><small>{money(r.wholesalePence)} recorded wholesale</small></div></article>)}</div></section><section className="panel" style={{marginTop:20,padding:18}}><h2>Customer values</h2><div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr><th align="left">Company</th><th align="left">Status</th><th align="right">Wholesale</th><th align="right">Retail</th></tr></thead><tbody>{portfolio.map(c=><tr key={c.companyId}><td>{c.companyName}</td><td>{c.subscriptionStatus}</td><td align="right">{money(c.wholesaleMonthlyPence)}</td><td align="right">{money(c.retailMonthlyPence)}</td></tr>)}</tbody></table></div></section></section>;}
