import { useEffect, useState } from "react";
import { api } from "../../lib/api";

type Reseller={id:string;name:string;slug:string;status:string;customers:number;vehicles:number;wholesalePence:number;supportEmail:string|null;wholesaleModel:string};
type Customer={id:string;name:string;slug:string;subscriptionPlan:string;subscriptionStatus:string;trialEndsAt:string|null;vehicleLimit:number;vehicleUsage:number;wholesaleMonthlyPence:number|null;retailMonthlyPence:number|null};
const money=(p:number|null|undefined)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format((p??0)/100);

export function ResellerPortalPage() {
  const [resellers,setResellers]=useState<Reseller[]>([]); const [selected,setSelected]=useState<string>(""); const [customers,setCustomers]=useState<Customer[]>([]); const [message,setMessage]=useState("");
  const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [email,setEmail]=useState(""); const [memberEmail,setMemberEmail]=useState("");
  async function load(){const rows=await api<Reseller[]>("/resellers");setResellers(rows);if(!selected&&rows[0])setSelected(rows[0].id);}
  useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Could not load resellers"));},[]);
  useEffect(()=>{if(!selected){setCustomers([]);return;}void api<Customer[]>(`/resellers/${selected}/customers`).then(setCustomers).catch(e=>setMessage(e instanceof Error?e.message:"Could not load reseller customers"));},[selected]);
  async function create(event:React.FormEvent){event.preventDefault();setMessage("");try{const r=await api<Reseller>("/resellers",{method:"POST",body:JSON.stringify({name,slug,supportEmail:email||undefined,wholesaleModel:"PER_TENANT",branding:{}})});setName("");setSlug("");setEmail("");setSelected(r.id);setMessage("Reseller created");await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not create reseller");}}
  async function grant(event:React.FormEvent){event.preventDefault();if(!selected)return;setMessage("");try{await api(`/resellers/${selected}/members`,{method:"POST",body:JSON.stringify({email:memberEmail,role:"ADMIN"})});setMemberEmail("");setMessage("Reseller administrator access granted");}catch(e){setMessage(e instanceof Error?e.message:"Could not grant reseller access");}}
  const current=resellers.find(r=>r.id===selected);
  return <div className="page-shell">
    <div className="page-heading"><div><p className="eyebrow">White label</p><h1>Reseller Portal</h1><p>Platform-owner controls for creating agent channels, granting reseller access and tracking their customer fleets without exposing FleetOS platform administration.</p></div></div>
    {message&&<p className="form-message">{message}</p>}
    <div className="stat-grid"><article className="stat-card"><span>Resellers</span><strong>{resellers.length}</strong></article><article className="stat-card"><span>Customer companies</span><strong>{resellers.reduce((n,r)=>n+r.customers,0)}</strong></article><article className="stat-card"><span>Vehicles through resellers</span><strong>{resellers.reduce((n,r)=>n+r.vehicles,0)}</strong></article><article className="stat-card"><span>Wholesale MRR recorded</span><strong>{money(resellers.reduce((n,r)=>n+r.wholesalePence,0))}</strong></article></div>
    <section className="dashboard-section"><p className="eyebrow">Create channel</p><h2>New reseller / agent</h2><form onSubmit={create} className="form-grid"><label>Trading name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))} placeholder="abc-fleet"/></label><label>Support email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><div><button className="primary-button" type="submit">Create reseller</button></div></form></section>
    <section className="dashboard-section"><p className="eyebrow">Reseller account</p><h2>Manage channel</h2>{resellers.length===0?<p>Create the first reseller above.</p>:<><label>Reseller<select value={selected} onChange={e=>setSelected(e.target.value)}>{resellers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{current&&<div className="action-grid" style={{marginTop:18}}><article className="action-card"><strong>{current.name}</strong><span>{current.status} · {current.wholesaleModel}</span></article><article className="action-card"><strong>{current.customers} customers</strong><span>{current.vehicles} vehicles</span></article><article className="action-card"><strong>{money(current.wholesalePence)}</strong><span>Recorded wholesale monthly value</span></article><article className="action-card"><strong>{current.supportEmail??"No support email"}</strong><span>Reseller-facing support identity</span></article></div>}</>}</section>
    {selected&&<section className="dashboard-section"><p className="eyebrow">Agent access</p><h2>Grant reseller administrator</h2><form onSubmit={grant} className="form-grid"><label>FleetOS account email<input required type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} placeholder="agent@company.co.uk"/></label><div><button type="submit">Grant reseller admin</button></div></form><p className="subtle">The email must already have a FleetOS user identity. Reseller membership is separate from PLATFORM_ADMIN.</p></section>}
    {selected&&<section className="dashboard-section"><p className="eyebrow">Customer companies</p><h2>{current?.name??"Reseller"} portfolio</h2>{customers.length===0?<p>No customer companies are linked to this reseller yet.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Company</th><th align="left">Status</th><th align="right">Vehicles</th><th align="right">Wholesale</th><th align="right">Retail</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><strong>{c.name}</strong><br/><small>{c.slug}</small></td><td>{c.subscriptionPlan} · {c.subscriptionStatus}</td><td align="right">{c.vehicleUsage}/{c.vehicleLimit}</td><td align="right">{money(c.wholesaleMonthlyPence)}</td><td align="right">{money(c.retailMonthlyPence)}</td></tr>)}</tbody></table></div>}</section>}
    <section className="dashboard-section"><p className="eyebrow">Permission boundary</p><h2>What resellers cannot change</h2><p>Security policy, tenant isolation, database rules, platform legal controls, core audit behaviour, infrastructure and master billing configuration remain under FleetOS platform ownership.</p></section>
  </div>;
}
