import { useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";

type Reseller={id:string;name:string};
type Branding={name:string;tagline:string;logoUrl:string|null;primaryColor:string;accentColor:string;sidebarColor:string;supportEmail:string|null;supportPhone:string|null;showPoweredBy:boolean;marketplaceEnabled:boolean};
const defaults:Branding={name:"FleetOS",tagline:"Transport operations, made simpler",logoUrl:null,primaryColor:"#197B58",accentColor:"#32C58B",sidebarColor:"#0E1B2C",supportEmail:null,supportPhone:null,showPoweredBy:true,marketplaceEnabled:true};

export function ResellerBrandingPage(){
  const [resellers,setResellers]=useState<Reseller[]>([]);const [selected,setSelected]=useState("");const [branding,setBranding]=useState<Branding>(defaults);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{void api<Reseller[]>("/resellers/mine").then(rows=>{setResellers(rows);if(rows[0])setSelected(rows[0].id);}).catch(e=>setMessage(e instanceof Error?e.message:"Could not load reseller account"));},[]);
  useEffect(()=>{if(!selected)return;void api<Branding>(`/resellers/${selected}/branding`).then(setBranding).catch(e=>setMessage(e instanceof Error?e.message:"Could not load branding"));},[selected]);
  const safeLogo=useMemo(()=>branding.logoUrl?.startsWith("https://")?branding.logoUrl:null,[branding.logoUrl]);
  const change=<K extends keyof Branding>(key:K,value:Branding[K])=>setBranding(current=>({...current,[key]:value}));
  async function save(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setMessage("");try{const next=await api<Branding>(`/resellers/${selected}/branding`,{method:"PATCH",body:JSON.stringify(branding)});setBranding(next);setMessage("Branding saved. Linked white-label customer apps now use this identity.");}catch(err){setMessage(err instanceof Error?err.message:"Could not save branding");}finally{setBusy(false);}}
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">White-label · Branding</p><h1>Your customer-facing identity</h1><p className="subtle">These settings are applied to customer companies linked to your reseller channel. FleetOS manager controls remain separate and are never exposed here.</p></div></div>{message&&<p className="form-message">{message}</p>}
    {resellers.length>1&&<label>Reseller account<select value={selected} onChange={e=>setSelected(e.target.value)}>{resellers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18,alignItems:"start"}}>
      <form className="panel" style={{padding:18}} onSubmit={save}><h2>Brand settings</h2><div className="form-grid"><label>Product name<input value={branding.name} onChange={e=>change("name",e.target.value)}/></label><label>Tagline<input value={branding.tagline} onChange={e=>change("tagline",e.target.value)}/></label><label>Logo URL (HTTPS)<input type="url" value={branding.logoUrl??""} onChange={e=>change("logoUrl",e.target.value||null)} placeholder="https://…"/></label><label>Support email<input type="email" value={branding.supportEmail??""} onChange={e=>change("supportEmail",e.target.value||null)}/></label><label>Support phone<input value={branding.supportPhone??""} onChange={e=>change("supportPhone",e.target.value||null)}/></label><label>Primary colour<input type="color" value={branding.primaryColor} onChange={e=>change("primaryColor",e.target.value.toUpperCase())}/></label><label>Accent colour<input type="color" value={branding.accentColor} onChange={e=>change("accentColor",e.target.value.toUpperCase())}/></label><label>Sidebar colour<input type="color" value={branding.sidebarColor} onChange={e=>change("sidebarColor",e.target.value.toUpperCase())}/></label><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={branding.showPoweredBy} onChange={e=>change("showPoweredBy",e.target.checked)}/> Show “Powered by FleetOS”</label><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={branding.marketplaceEnabled} onChange={e=>change("marketplaceEnabled",e.target.checked)}/> Marketplace enabled</label></div><button className="primary-button" disabled={busy}>{busy?"Saving…":"Save white-label branding"}</button></form>
      <section className="panel" style={{padding:0,overflow:"hidden"}}><div style={{background:branding.sidebarColor,color:"white",padding:20,display:"flex",gap:12,alignItems:"center"}}>{safeLogo?<img src={safeLogo} alt="" style={{width:42,height:42,objectFit:"contain",borderRadius:8,background:"white"}}/>:<span style={{width:42,height:42,borderRadius:10,display:"grid",placeItems:"center",background:branding.primaryColor,fontWeight:800}}>{branding.name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</span>}<div><strong style={{display:"block",fontSize:20}}>{branding.name||"Your brand"}</strong><small>{branding.tagline||"Your tagline"}</small></div></div><div style={{padding:22}}><p className="eyebrow">Live preview</p><h2>Customer workspace</h2><p className="subtle">Your linked fleets will see this branding in their normal customer app.</p><button style={{background:branding.primaryColor,borderColor:branding.primaryColor,color:"white"}}>Primary action</button><span style={{display:"inline-block",marginLeft:10,padding:"9px 12px",borderRadius:8,background:branding.accentColor,color:"#07150f",fontWeight:700}}>Accent</span>{branding.showPoweredBy&&<p className="subtle" style={{marginTop:24}}>Powered by FleetOS</p>}</div></section>
    </div>
  </section>;
}
