import { useEffect, useState } from "react";
import { api } from "../../lib/api";

type Reseller={id:string;name:string;slug:string;status:string;customers:number;vehicles:number;supportEmail:string|null;wholesaleModel:string;role:string};
type Customer={id:string;name:string;slug:string;subscriptionPlan:string;subscriptionStatus:string;trialEndsAt:string|null;vehicleLimit:number;vehicleUsage:number;wholesaleMonthlyPence:number|null;retailMonthlyPence:number|null};

export function ResellerPortalPage(){
  const [resellers,setResellers]=useState<Reseller[]>([]);const [selected,setSelected]=useState("");const [customers,setCustomers]=useState<Customer[]>([]);const [message,setMessage]=useState("");const [customerInviteUrl,setCustomerInviteUrl]=useState("");
  async function load(){const rows=await api<Reseller[]>("/resellers/mine");setResellers(rows);if(!selected&&rows[0])setSelected(rows[0].id);}
  useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Could not load reseller portal"));},[]);
  useEffect(()=>{if(!selected){setCustomers([]);return;}void api<Customer[]>(`/resellers/${selected}/customers`).then(setCustomers).catch(e=>setMessage(e instanceof Error?e.message:"Could not load reseller customers"));},[selected]);
  async function createCustomerInvite(){if(!selected)return;setMessage("");setCustomerInviteUrl("");try{const result=await api<{customerUrl:string;expiresAt:string}>(`/resellers/${selected}/customer-invites`,{method:"POST",body:JSON.stringify({expiresInDays:14})});setCustomerInviteUrl(result.customerUrl);setMessage("Customer onboarding link created. It expires in 14 days and can only be used once.");}catch(e){setMessage(e instanceof Error?e.message:"Could not create customer invitation");}}
  async function copy(text:string){try{await navigator.clipboard.writeText(text);setMessage("Link copied.");}catch{window.prompt("Copy this link",text);}}
  const current=resellers.find(r=>r.id===selected);
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">White-label partner</p><h1>{current?.name??"Reseller portal"}</h1><p className="subtle">Manage only the fleets sold through your channel. FleetOS owner controls, global customer lists and infrastructure are not available in this portal.</p></div></div>{message&&<p className="form-message">{message}</p>}
    {resellers.length>1&&<label>Reseller account<select value={selected} onChange={e=>setSelected(e.target.value)}>{resellers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
    <div className="metric-grid"><article className="metric-card"><div><p>Customer companies</p><strong>{current?.customers??0}</strong></div></article><article className="metric-card"><div><p>Vehicles</p><strong>{current?.vehicles??0}</strong></div></article><article className="metric-card"><div><p>Your role</p><strong>{current?.role??"—"}</strong></div></article></div>
    {selected&&<section className="panel" style={{marginTop:20,padding:18}}><h2>Add a customer fleet</h2><p className="subtle">Generate a one-time customer onboarding link. It creates a normal isolated fleet company, links it to your channel and automatically applies your current white-label branding.</p><button className="primary-button" onClick={()=>void createCustomerInvite()}>Generate customer link</button>{customerInviteUrl&&<div style={{marginTop:14}}><strong>One-time customer URL</strong><p style={{wordBreak:"break-all"}}>{customerInviteUrl}</p><button className="secondary-button" onClick={()=>void copy(customerInviteUrl)}>Copy customer link</button></div>}</section>}
    {selected&&<section className="panel" style={{marginTop:20,padding:18}}><h2>Customer portfolio</h2>{!customers.length?<p>No customer companies are linked to this reseller yet.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr><th align="left">Company</th><th align="left">Subscription</th><th align="right">Vehicles</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><strong>{c.name}</strong><br/><small>{c.slug}</small></td><td>{c.subscriptionPlan} · {c.subscriptionStatus}</td><td align="right">{c.vehicleUsage}/{c.vehicleLimit}</td></tr>)}</tbody></table></div>}</section>}
  </section>;
}
