import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, CheckCircle2, ClipboardCheck, Coins, MapPin, MessageSquarePlus, RefreshCw, Users } from "lucide-react";
import { api } from "../../lib/api";
import type { FormField } from "./types";

type Detail={id:string;reference:string;title:string;description:string|null;status:string;priority:string;source:string;jobTypeName:string;trade:string;colour:string;riskAssessmentRequired:boolean;customerSignatureRequired:boolean;customerName:string;siteName:string|null;siteAddress:string|null;sitePostcode:string|null;accessNotes:string|null;assetName:string|null;assetReference:string|null;manufacturer:string|null;model:string|null;serialNumber:string|null;registration:string|null;scheduledStart:string|null;scheduledEnd:string|null;dueAt:string|null;contactName:string|null;contactPhone:string|null;contactEmail:string|null;purchaseOrderNumber:string|null;quotePence:number|null;worksheetSchema:FormField[];worksheetResponses:Record<string,unknown>;riskAssessment:Record<string,unknown>;customerSignature:Record<string,unknown>;assignments:Array<{id:string;firstName:string;lastName:string;personType:string;status:string}>;visits:Array<{id:string;title:string;status:string;scheduledStart:string|null;actualStart:string|null;actualEnd:string|null}>;timeline:Array<{id:string;type:string;summary:string;detail:string|null;createdAt:string}>;costs:Array<{id:string;category:string;description:string;quantity:number;unitCostPence:number;unitSellPence:number}>;documents:Array<{id:string;name:string;type:string;fileUrl:string;createdAt:string}>;canManage:boolean;financialAccess:boolean};
const officeStatuses=["PLANNED","ASSIGNED","SCHEDULED","DISPATCHED","TRAVELLING","ON_SITE","PAUSED","COMPLETED","COMPLETED_ISSUES","CLOSED","CANCELLED"];
const fieldStatuses=["TRAVELLING","ON_SITE","PAUSED","COMPLETED","COMPLETED_ISSUES"];
const label=(value:string)=>value.replaceAll("_"," "); const dateTime=(value:string|null)=>value?new Date(value).toLocaleString("en-GB"):"Not set"; const pounds=(pence:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100);

export function JobDetails({id,onClose,onChanged,fieldMode=false}:{id:string;onClose:()=>void;onChanged:()=>Promise<void>;fieldMode?:boolean}){
  const [job,setJob]=useState<Detail|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [note,setNote]=useState("");const [responses,setResponses]=useState<Record<string,unknown>>({});const [riskSafe,setRiskSafe]=useState(false);const [signature,setSignature]=useState("");const [cost,setCost]=useState({category:"MATERIAL",description:"",quantity:"1",unitCost:"",unitSell:""});
  async function load(){setMessage("");try{const next=await api<Detail>(`/jobs/${id}`);setJob(next);setResponses(next.worksheetResponses??{});setRiskSafe(Boolean(next.riskAssessment?.safeToProceed));setSignature(String(next.customerSignature?.name??""));}catch(error){setMessage(error instanceof Error?error.message:"Could not load the job.");}}
  useEffect(()=>{void load();},[id]);
  const totals=useMemo(()=>job?.costs.reduce((sum,line)=>({cost:sum.cost+line.quantity*line.unitCostPence,sell:sum.sell+line.quantity*line.unitSellPence}),{cost:0,sell:0})??{cost:0,sell:0},[job?.costs]);
  async function status(value:string){setBusy(true);try{await api(`/jobs/${id}/status`,{method:"PATCH",body:JSON.stringify({status:value})});await Promise.all([load(),onChanged()]);}catch(error){setMessage(error instanceof Error?error.message:"Could not update status.");}finally{setBusy(false);}}
  async function addNote(event:FormEvent){event.preventDefault();if(!note.trim())return;setBusy(true);try{await api(`/jobs/${id}/timeline`,{method:"POST",body:JSON.stringify({detail:note})});setNote("");await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not add note.");}finally{setBusy(false);}}
  async function saveWorksheet(event:FormEvent){event.preventDefault();if(job?.riskAssessmentRequired&&!riskSafe)return setMessage("Confirm the risk assessment before saving the field sheet.");if(job?.customerSignatureRequired&&!signature.trim())return setMessage("Enter the customer signature name.");setBusy(true);try{await api(`/jobs/${id}/worksheet`,{method:"POST",body:JSON.stringify({responses,riskAssessment:{safeToProceed:riskSafe,confirmedAt:new Date().toISOString()},customerSignature:signature?{name:signature}:undefined})});setMessage("Job sheet saved to the office record.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not save the job sheet.");}finally{setBusy(false);}}
  async function addCost(event:FormEvent){event.preventDefault();setBusy(true);try{await api(`/jobs/${id}/costs`,{method:"POST",body:JSON.stringify({category:cost.category,description:cost.description,quantity:Number(cost.quantity),unitCostPence:Math.round(Number(cost.unitCost)*100),unitSellPence:Math.round(Number(cost.unitSell)*100)})});setCost(current=>({...current,description:"",unitCost:"",unitSell:""}));await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not add the cost line.");}finally{setBusy(false);}}
  if(!job)return <section className="panel job-detail loading-page"><div><RefreshCw className="spin"/><h2>Loading work order</h2>{message&&<p>{message}</p>}</div></section>;
  const statuses=fieldMode?[job.status,...fieldStatuses.filter((value)=>value!==job.status)]:officeStatuses;
  return <section className="job-detail"><button type="button" className="secondary-button back" onClick={onClose}><ArrowLeft/> Back to jobs</button><div className="job-detail-hero panel" style={{"--job-colour":job.colour} as React.CSSProperties}><div><p className="eyebrow">{job.trade} · {job.jobTypeName}</p><h1>{job.reference} · {job.title}</h1><p>{job.description||"No scope description entered."}</p></div><div><span className={`job-priority ${job.priority.toLowerCase()}`}>{job.priority}</span><select aria-label="Job status" value={job.status} disabled={busy||(!job.canManage&&!fieldMode)} onChange={e=>void status(e.target.value)}>{statuses.map(value=><option key={value}>{label(value)}</option>)}</select></div></div>{message&&<p role="status" className="form-message">{message}</p>}
    <div className="job-detail-grid"><div className="job-detail-main"><section className="panel job-summary-grid"><article><MapPin/><div><small>Customer and site</small><strong>{job.customerName}</strong><p>{job.siteName} · {job.siteAddress} {job.sitePostcode}</p>{job.accessNotes&&<em>{job.accessNotes}</em>}</div></article><article><CalendarClock/><div><small>Appointment / SLA</small><strong>{dateTime(job.scheduledStart)}</strong><p>Ends {dateTime(job.scheduledEnd)} · due {dateTime(job.dueAt)}</p></div></article><article><Users/><div><small>Allocated team</small><strong>{job.assignments.length?job.assignments.map(person=>`${person.firstName} ${person.lastName}`).join(", "):"Unallocated"}</strong><p>{job.registration?`Vehicle ${job.registration}`:"No vehicle allocated"}</p></div></article><article><ClipboardCheck/><div><small>Asset and contact</small><strong>{job.assetName||"No linked asset"}</strong><p>{job.contactName||"No contact"} {job.contactPhone}</p></div></article></section>
      <form className="panel job-sheet" onSubmit={saveWorksheet}><div className="panel-heading"><div><h2>Digital job sheet</h2><p>Field answers sync immediately to this office record.</p></div><ClipboardCheck/></div>{job.riskAssessmentRequired&&<label className="risk-confirm"><input type="checkbox" checked={riskSafe} onChange={e=>setRiskSafe(e.target.checked)}/><span><strong>Point-of-work risk assessment completed</strong><small>I have reviewed the hazards and it is safe to proceed.</small></span></label>}<div className="form-grid">{job.worksheetSchema.map(field=>field.type==="CHECKBOX"?<label className="job-check" key={field.key}><input type="checkbox" checked={Boolean(responses[field.key])} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.checked}))}/><span>{field.label}{field.required?" *":""}</span></label>:field.type==="TEXTAREA"?<label key={field.key}>{field.label}{field.required?" *":""}<textarea value={String(responses[field.key]??"")} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.value}))}/></label>:field.type==="SELECT"?<label key={field.key}>{field.label}{field.required?" *":""}<select value={String(responses[field.key]??"")} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.value}))}><option value="">Choose…</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select></label>:<label key={field.key}>{field.label}{field.required?" *":""}<input type={field.type==="DATE"?"date":field.type==="NUMBER"?"number":"text"} value={String(responses[field.key]??"")} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.value}))}/></label>)}</div>{job.customerSignatureRequired&&<label>Customer signature name *<input value={signature} onChange={e=>setSignature(e.target.value)} placeholder="Type the signatory's full name"/></label>}<button className="primary-button" disabled={busy}>Save job sheet</button></form>
      <section className="panel"><div className="panel-heading"><div><h2>Job timeline</h2><p>Office and field activity in one audit trail.</p></div></div><form className="timeline-note" onSubmit={addNote}><MessageSquarePlus/><input aria-label="Job timeline note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add job note, customer update or handover…"/><button type="submit" disabled={busy}>Add</button></form><div className="job-timeline">{job.timeline.map(item=><article key={item.id}><span></span><div><strong>{item.summary}</strong><small>{new Date(item.createdAt).toLocaleString("en-GB")} · {label(item.type)}</small>{item.detail&&<p>{item.detail}</p>}</div></article>)}</div></section>
    </div><aside><section className="panel job-finance"><div className="panel-heading"><div><h2>{job.financialAccess?"Costs and value":"Parts and materials"}</h2><p>{job.financialAccess?"Job-level margin visibility.":"Record items used on this job."}</p></div><Coins/></div>{job.financialAccess&&<dl><div><dt>Quoted</dt><dd>{pounds(job.quotePence??0)}</dd></div><div><dt>Actual cost</dt><dd>{pounds(totals.cost)}</dd></div><div><dt>Recorded sell</dt><dd>{pounds(totals.sell)}</dd></div><div><dt>Margin</dt><dd>{pounds((job.quotePence??totals.sell)-totals.cost)}</dd></div></dl>}<form onSubmit={addCost}><select aria-label="Cost category" value={cost.category} onChange={e=>setCost(current=>({...current,category:e.target.value}))}>{["LABOUR","PART","MATERIAL","EXPENSE","SUBCONTRACT","OTHER"].map(value=><option key={value}>{value}</option>)}</select><input aria-label="Cost description" required value={cost.description} onChange={e=>setCost(current=>({...current,description:e.target.value}))} placeholder="Part, labour or expense"/><div><input aria-label="Quantity" required type="number" min="0.001" step="0.001" value={cost.quantity} onChange={e=>setCost(current=>({...current,quantity:e.target.value}))} placeholder="Qty"/>{job.financialAccess&&<input aria-label="Unit cost" required type="number" min="0" step="0.01" value={cost.unitCost} onChange={e=>setCost(current=>({...current,unitCost:e.target.value}))} placeholder="Unit cost £"/>}</div>{job.financialAccess&&<input aria-label="Unit sell price" required type="number" min="0" step="0.01" value={cost.unitSell} onChange={e=>setCost(current=>({...current,unitSell:e.target.value}))} placeholder="Unit sell £"/>}<button type="submit" disabled={busy}>Add cost line</button></form>{job.costs.map(line=><article key={line.id}><strong>{line.description}</strong><small>{line.quantity}{job.financialAccess?` × ${pounds(line.unitCostPence)} cost · ${pounds(line.unitSellPence)} sell`:" recorded"}</small></article>)}</section><section className="panel job-controls"><h2>Completion controls</h2><p><CheckCircle2/> Risk: {job.riskAssessmentRequired?job.riskAssessment?.safeToProceed?"signed":"required":"optional"}</p><p><CheckCircle2/> Customer signature: {job.customerSignatureRequired?job.customerSignature?.name?String(job.customerSignature.name):"required":"optional"}</p><p><CheckCircle2/> Documents: {job.documents.length}</p><p><CheckCircle2/> PO: {job.purchaseOrderNumber||"not supplied"}</p>{fieldMode&&<div className="field-status-actions"><button type="button" onClick={()=>void status("TRAVELLING")}>Travelling</button><button type="button" onClick={()=>void status("ON_SITE")}>On site</button><button type="button" onClick={()=>void status("PAUSED")}>Pause</button><button type="button" className="primary-button" onClick={()=>void status("COMPLETED")}>Complete</button></div>}</section></aside></div>
  </section>;
}
