import { DragEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, CheckCircle2, ClipboardCheck, Coins, ExternalLink, FileText, MapPin, MessageSquarePlus, RefreshCw, UploadCloud, Users } from "lucide-react";
import { api, ACTIVE_WORKSPACE_KEY } from "../../lib/api";
import { supabase } from "../../lib/supabase";
import type { FormField } from "./types";

type Detail={id:string;reference:string;title:string;description:string|null;status:string;priority:string;source:string;jobTypeName:string;trade:string;colour:string;riskAssessmentRequired:boolean;customerSignatureRequired:boolean;customerName:string;siteName:string|null;siteAddress:string|null;sitePostcode:string|null;accessNotes:string|null;assetName:string|null;assetReference:string|null;manufacturer:string|null;model:string|null;serialNumber:string|null;registration:string|null;scheduledStart:string|null;scheduledEnd:string|null;dueAt:string|null;contactName:string|null;contactPhone:string|null;contactEmail:string|null;purchaseOrderNumber:string|null;quotePence:number|null;worksheetSchema:FormField[];worksheetResponses:Record<string,unknown>;riskAssessment:Record<string,unknown>;customerSignature:Record<string,unknown>;assignments:Array<{id:string;firstName:string;lastName:string;personType:string;status:string}>;visits:Array<{id:string;title:string;status:string;scheduledStart:string|null;actualStart:string|null;actualEnd:string|null}>;timeline:Array<{id:string;type:string;summary:string;detail:string|null;createdAt:string}>;costs:Array<{id:string;category:string;description:string;quantity:number;unitCostPence:number;unitSellPence:number}>;documents:Array<{id:string;name:string;type:string;fileUrl:string;createdAt:string}>;canManage:boolean;financialAccess:boolean};
const officeStatuses=["PLANNED","ASSIGNED","SCHEDULED","DISPATCHED","TRAVELLING","ON_SITE","PAUSED","COMPLETED","COMPLETED_ISSUES","CLOSED","CANCELLED"];
const fieldStatuses=["TRAVELLING","ON_SITE","PAUSED","COMPLETED","COMPLETED_ISSUES"];
const paperworkTypes=[
  {value:"RAMS",label:"RAMS / method statement"},
  {value:"CERTIFICATE",label:"Test certificate / certificate"},
  {value:"POD",label:"Proof of delivery"},
  {value:"FIELD_PAPERWORK",label:"Other field-generated paperwork"},
  {value:"SERVICE_RECORD",label:"Service record"},
  {value:"INVOICE",label:"Invoice / commercial document"},
  {value:"OTHER",label:"Other office document"},
];
const driverPaperworkTypes=paperworkTypes.filter(option=>["POD","FIELD_PAPERWORK"].includes(option.value));
const label=(value:string)=>value.replaceAll("_"," "); const dateTime=(value:string|null)=>value?new Date(value).toLocaleString("en-GB"):"Not set"; const pounds=(pence:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(pence/100);
function cleanFilename(name:string){const safe=name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(-160);return safe||"job-paperwork";}

export function JobDetails({id,onClose,onChanged,fieldMode=false}:{id:string;onClose:()=>void;onChanged:()=>Promise<void>;fieldMode?:boolean}){
  const [job,setJob]=useState<Detail|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [note,setNote]=useState("");const [responses,setResponses]=useState<Record<string,unknown>>({});const [riskSafe,setRiskSafe]=useState(false);const [signature,setSignature]=useState("");const [cost,setCost]=useState({category:"MATERIAL",description:"",quantity:"1",unitCost:"",unitSell:""});
  const [paperworkType,setPaperworkType]=useState(fieldMode?"POD":"RAMS");const [uploading,setUploading]=useState(false);const [dragging,setDragging]=useState(false);
  async function load(){setMessage("");try{const next=await api<Detail>(`/jobs/${id}`);setJob(next);setResponses(next.worksheetResponses??{});setRiskSafe(Boolean(next.riskAssessment?.safeToProceed));setSignature(String(next.customerSignature?.name??""));}catch(error){setMessage(error instanceof Error?error.message:"Could not load the job.");}}
  useEffect(()=>{void load();},[id]);
  const totals=useMemo(()=>job?.costs.reduce((sum,line)=>({cost:sum.cost+line.quantity*line.unitCostPence,sell:sum.sell+line.quantity*line.unitSellPence}),{cost:0,sell:0})??{cost:0,sell:0},[job?.costs]);
  async function status(value:string){setBusy(true);setMessage("");try{await api(`/jobs/${id}/status`,{method:"PATCH",body:JSON.stringify({status:value})});setMessage(`Job status updated to ${label(value).toLowerCase()}.`);await Promise.all([load(),onChanged()]);}catch(error){setMessage(error instanceof Error?error.message:"Could not update status.");}finally{setBusy(false);}}
  async function addNote(event:FormEvent){event.preventDefault();if(!note.trim())return;setBusy(true);try{await api(`/jobs/${id}/timeline`,{method:"POST",body:JSON.stringify({detail:note})});setNote("");await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not add note.");}finally{setBusy(false);}}
  async function saveWorksheet(event:FormEvent){event.preventDefault();if(job?.riskAssessmentRequired&&!riskSafe)return setMessage("Confirm the risk assessment before saving the field sheet.");if(job?.customerSignatureRequired&&!signature.trim())return setMessage("Enter the customer signature name.");setBusy(true);try{await api(`/jobs/${id}/worksheet`,{method:"POST",body:JSON.stringify({responses,riskAssessment:{safeToProceed:riskSafe,confirmedAt:new Date().toISOString()},customerSignature:signature?{name:signature}:undefined})});setMessage("Job sheet saved to the office record.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not save the job sheet.");}finally{setBusy(false);}}
  async function addCost(event:FormEvent){event.preventDefault();setBusy(true);try{await api(`/jobs/${id}/costs`,{method:"POST",body:JSON.stringify({category:cost.category,description:cost.description,quantity:Number(cost.quantity),unitCostPence:Math.round(Number(cost.unitCost)*100),unitSellPence:Math.round(Number(cost.unitSell)*100)})});setCost(current=>({...current,description:"",unitCost:"",unitSell:""}));await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not add the cost line.");}finally{setBusy(false);}}
  async function uploadPaperwork(file:File){const companyId=localStorage.getItem(ACTIVE_WORKSPACE_KEY);if(!companyId)return setMessage("No active company workspace is selected.");if(file.size>20*1024*1024)return setMessage("Job paperwork must be 20 MB or smaller per file.");const folder=fieldMode?"field/":"";const path=`${companyId}/jobs/${id}/${folder}${crypto.randomUUID()}-${cleanFilename(file.name)}`;setUploading(true);setMessage("");try{const {error:storageError}=await supabase.storage.from("fleet-documents").upload(path,file,{upsert:false,contentType:file.type||undefined});if(storageError)throw storageError;try{await api(`/documents/job/${id}`,{method:"POST",body:JSON.stringify({name:file.name,storagePath:path,type:paperworkType,fileSize:file.size,mimeType:file.type||undefined})});}catch(apiError){await supabase.storage.from("fleet-documents").remove([path]).catch(()=>undefined);throw apiError;}setMessage(`${file.name} added to this job.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Could not upload job paperwork.");}finally{setUploading(false);setDragging(false);}}
  async function openPaperwork(document:Detail["documents"][number]){setMessage("");const {data,error}=await supabase.storage.from("fleet-documents").createSignedUrl(document.fileUrl,60);if(error||!data?.signedUrl)return setMessage(error?.message||"Could not open this job document.");window.open(data.signedUrl,"_blank","noopener,noreferrer");}
  function dropPaperwork(event:DragEvent<HTMLDivElement>){event.preventDefault();setDragging(false);const file=event.dataTransfer.files?.[0];if(file)void uploadPaperwork(file);}
  if(!job)return <section className="panel job-detail loading-page"><div><RefreshCw className="spin"/><h2>Loading work order</h2>{message&&<p>{message}</p>}</div></section>;
  const statuses=fieldMode?[job.status,...fieldStatuses.filter((value)=>value!==job.status)]:officeStatuses;
  const completed=["COMPLETED","COMPLETED_ISSUES","CLOSED"].includes(job.status);
  return <section className="job-detail"><button type="button" className="secondary-button back" onClick={onClose}><ArrowLeft/> Back to jobs</button><div className="job-detail-hero panel" style={{"--job-colour":job.colour} as React.CSSProperties}><div><p className="eyebrow">{job.trade} · {job.jobTypeName}</p><h1>{job.reference} · {job.title}</h1><p>{job.description||"No scope description entered."}</p></div><div><span className={`job-priority ${job.priority.toLowerCase()}`}>{job.priority}</span><select aria-label="Job status" value={job.status} disabled={busy||(!job.canManage&&!fieldMode)} onChange={e=>void status(e.target.value)}>{statuses.map(value=><option key={value}>{label(value)}</option>)}</select></div></div>{message&&<p role="status" className="form-message">{message}</p>}
    {fieldMode&&<section className="panel job-progress-panel"><div><p className="eyebrow">Job progress</p><h2>Tell the office where you are in the job</h2><p>Current status: <strong>{label(job.status)}</strong>. Changes update the office record immediately.</p></div><div className="job-progress-actions"><button type="button" disabled={busy||job.status==="TRAVELLING"||completed} onClick={()=>void status("TRAVELLING")}>Travelling</button><button type="button" disabled={busy||job.status==="ON_SITE"||completed} onClick={()=>void status("ON_SITE")}>On site</button><button type="button" disabled={busy||job.status==="PAUSED"||completed} onClick={()=>void status("PAUSED")}>Pause</button><button type="button" className="primary-button" disabled={busy||completed} onClick={()=>void status("COMPLETED")}>Job complete</button></div></section>}
    {!fieldMode&&job.canManage&&<section className="panel office-completion-panel"><div><p className="eyebrow">Office completion</p><h2>Job outcome</h2><p>Mark the work finished here. Required job-sheet, RAMS/risk and signature controls still have to be satisfied before completion.</p></div><div className="office-completion-actions"><button type="button" className="primary-button" disabled={busy||job.status==="COMPLETED"||job.status==="CLOSED"} onClick={()=>void status("COMPLETED")}>Mark job complete</button><button type="button" disabled={busy||job.status==="COMPLETED_ISSUES"||job.status==="CLOSED"} onClick={()=>void status("COMPLETED_ISSUES")}>Complete with issues</button>{["COMPLETED","COMPLETED_ISSUES"].includes(job.status)&&<button type="button" disabled={busy} onClick={()=>void status("CLOSED")}>Close job</button>}</div></section>}
    <div className="job-detail-grid"><div className="job-detail-main"><section className="panel job-summary-grid"><article><MapPin/><div><small>Customer and site</small><strong>{job.customerName}</strong><p>{job.siteName} · {job.siteAddress} {job.sitePostcode}</p>{job.accessNotes&&<em>{job.accessNotes}</em>}</div></article><article><CalendarClock/><div><small>Appointment / SLA</small><strong>{dateTime(job.scheduledStart)}</strong><p>Ends {dateTime(job.scheduledEnd)} · due {dateTime(job.dueAt)}</p></div></article><article><Users/><div><small>Allocated team</small><strong>{job.assignments.length?job.assignments.map(person=>`${person.firstName} ${person.lastName}`).join(", "):"Unallocated"}</strong><p>{job.registration?`Vehicle ${job.registration}`:"No vehicle allocated"}</p></div></article><article><ClipboardCheck/><div><small>Asset and contact</small><strong>{job.assetName||"No linked asset"}</strong><p>{job.contactName||"No contact"} {job.contactPhone}</p></div></article></section>
      <section className="panel job-paperwork"><div className="panel-heading"><div><h2>Job paperwork</h2><p>{fieldMode?"RAMS, method statements and certificates are read-only. You can add POD and other paperwork you create while completing this assigned job.":"Office can upload and manage all job document types. Files remain private and attached to this work order."}</p></div><FileText/></div>{fieldMode?<div className="driver-paperwork-add"><strong>Add field paperwork</strong><p className="subtle">Choose proof of delivery or another document produced on this job. Office-issued documents cannot be replaced here.</p><label className="paperwork-type">Document you are adding<select value={paperworkType} onChange={e=>setPaperworkType(e.target.value)}>{driverPaperworkTypes.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="secondary-button paperwork-file-button">{uploading?"Uploading paperwork…":"Choose file to add"}<input type="file" disabled={uploading} onChange={event=>{const file=event.target.files?.[0];if(file)void uploadPaperwork(file);event.currentTarget.value="";}}/></label><small>Private storage · maximum 20 MB</small></div>:<><label className="paperwork-type">Paperwork type<select value={paperworkType} onChange={e=>setPaperworkType(e.target.value)}>{paperworkTypes.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><div className={`job-dropzone ${dragging?"dragging":""}`} onDragOver={event=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={dropPaperwork}><UploadCloud/><strong>{uploading?"Uploading paperwork…":"Drag and drop paperwork here"}</strong><span>or choose a file · private storage · maximum 20 MB</span><label className="secondary-button">Choose file<input type="file" disabled={uploading} onChange={event=>{const file=event.target.files?.[0];if(file)void uploadPaperwork(file);event.currentTarget.value="";}}/></label></div></>}<div className="job-paperwork-list">{job.documents.length?job.documents.map(document=><article key={document.id}><FileText/><div><strong>{document.name}</strong><small>{label(document.type)} · {new Date(document.createdAt).toLocaleString("en-GB")}{fieldMode&&["RAMS","CERTIFICATE"].includes(document.type)?" · Read-only":fieldMode?" · Available to view":""}</small></div><button type="button" onClick={()=>void openPaperwork(document)}><ExternalLink/> Open</button></article>):<p className="subtle">No paperwork attached to this job yet.</p>}</div></section>
      <form className="panel job-sheet" onSubmit={saveWorksheet}><div className="panel-heading"><div><h2>Digital job sheet</h2><p>Field answers sync immediately to this office record.</p></div><ClipboardCheck/></div>{job.riskAssessmentRequired&&<label className="risk-confirm"><input type="checkbox" checked={riskSafe} onChange={e=>setRiskSafe(e.target.checked)}/><span><strong>Point-of-work risk assessment completed</strong><small>I have reviewed the hazards and it is safe to proceed.</small></span></label>}<div className="form-grid">{job.worksheetSchema.map(field=>field.type==="CHECKBOX"?<label className="job-check" key={field.key}><input type="checkbox" checked={Boolean(responses[field.key])} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.checked}))}/><span>{field.label}{field.required?" *":""}</span></label>:field.type==="TEXTAREA"?<label key={field.key}>{field.label}{field.required?" *":""}<textarea rows={5} value={String(responses[field.key]??"")} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.value}))}/></label>:field.type==="SELECT"?<label key={field.key}>{field.label}{field.required?" *":""}<select value={String(responses[field.key]??"")} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.value}))}><option value="">Choose…</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select></label>:<label key={field.key}>{field.label}{field.required?" *":""}<input type={field.type==="DATE"?"date":field.type==="NUMBER"?"number":"text"} value={String(responses[field.key]??"")} onChange={e=>setResponses(current=>({...current,[field.key]:e.target.value}))}/></label>)}</div>{job.customerSignatureRequired&&<label>Customer signature name *<input value={signature} onChange={e=>setSignature(e.target.value)} placeholder="Type the signatory's full name"/></label>}<button className="primary-button" disabled={busy}>Save job sheet</button></form>
      <section className="panel"><div className="panel-heading"><div><h2>Job timeline & notes</h2><p>Office and field activity in one audit trail.</p></div></div><form className="timeline-note" onSubmit={addNote}><MessageSquarePlus/><textarea aria-label="Job timeline note" rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a detailed job note, customer update, handover, access issue or anything the next person needs to know…"/><button type="submit" disabled={busy}>Add note</button></form><div className="job-timeline">{job.timeline.map(item=><article key={item.id}><span></span><div><strong>{item.summary}</strong><small>{new Date(item.createdAt).toLocaleString("en-GB")} · {label(item.type)}</small>{item.detail&&<p>{item.detail}</p>}</div></article>)}</div></section>
    </div><aside><section className="panel job-finance"><div className="panel-heading"><div><h2>{job.financialAccess?"Costs and value":"Parts and materials"}</h2><p>{job.financialAccess?"Job-level margin visibility.":"Record items used on this job."}</p></div><Coins/></div>{job.financialAccess&&<dl><div><dt>Quoted</dt><dd>{pounds(job.quotePence??0)}</dd></div><div><dt>Actual cost</dt><dd>{pounds(totals.cost)}</dd></div><div><dt>Recorded sell</dt><dd>{pounds(totals.sell)}</dd></div><div><dt>Margin</dt><dd>{pounds((job.quotePence??totals.sell)-totals.cost)}</dd></div></dl>}<form onSubmit={addCost}><select aria-label="Cost category" value={cost.category} onChange={e=>setCost(current=>({...current,category:e.target.value}))}>{["LABOUR","PART","MATERIAL","EXPENSE","SUBCONTRACT","OTHER"].map(value=><option key={value}>{value}</option>)}</select><input aria-label="Cost description" required value={cost.description} onChange={e=>setCost(current=>({...current,description:e.target.value}))} placeholder="Part, labour or expense"/><div><input aria-label="Quantity" required type="number" min="0.001" step="0.001" value={cost.quantity} onChange={e=>setCost(current=>({...current,quantity:e.target.value}))} placeholder="Qty"/>{job.financialAccess&&<input aria-label="Unit cost" required type="number" min="0" step="0.01" value={cost.unitCost} onChange={e=>setCost(current=>({...current,unitCost:e.target.value}))} placeholder="Unit cost £"/>}</div>{job.financialAccess&&<input aria-label="Unit sell price" required type="number" min="0" step="0.01" value={cost.unitSell} onChange={e=>setCost(current=>({...current,unitSell:e.target.value}))} placeholder="Unit sell £"/>}<button type="submit" disabled={busy}>Add cost line</button></form>{job.costs.map(line=><article key={line.id}><strong>{line.description}</strong><small>{line.quantity}{job.financialAccess?` × ${pounds(line.unitCostPence)} cost · ${pounds(line.unitSellPence)} sell`:" recorded"}</small></article>)}</section><section className="panel job-controls"><h2>Completion controls</h2><p><CheckCircle2/> Risk: {job.riskAssessmentRequired?job.riskAssessment?.safeToProceed?"signed":"required":"optional"}</p><p><CheckCircle2/> Customer signature: {job.customerSignatureRequired?job.customerSignature?.name?String(job.customerSignature.name):"required":"optional"}</p><p><CheckCircle2/> Documents: {job.documents.length}</p><p><CheckCircle2/> PO: {job.purchaseOrderNumber||"not supplied"}</p></section></aside></div>
  </section>;
}

