import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Check, MapPin, Users } from "lucide-react";
import { api } from "../../lib/api";
import type { JobConfig } from "./types";

type Form={jobTypeId:string;title:string;description:string;priority:string;customerId:string;customerName:string;siteId:string;siteName:string;siteAddress:string;sitePostcode:string;contactName:string;contactPhone:string;contactEmail:string;accessNotes:string;scheduledStart:string;scheduledEnd:string;personIds:string[];vehicleId:string;purchaseOrderNumber:string;reference:string};
const steps=["Job","Customer / site","When / who"];
const label=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase());

export function JobWizard({config,onComplete,onCancel}:{config:JobConfig;onComplete:()=>void;onCancel:()=>void}){
  const first=config.jobTypes[0];
  const [step,setStep]=useState(0);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const [form,setForm]=useState<Form>({jobTypeId:first?.id??"",title:"",description:"",priority:first?.defaultPriority??"NORMAL",customerId:"",customerName:"",siteId:"",siteName:"Main site",siteAddress:"",sitePostcode:"",contactName:"",contactPhone:"",contactEmail:"",accessNotes:"",scheduledStart:"",scheduledEnd:"",personIds:[],vehicleId:"",purchaseOrderNumber:"",reference:""});
  const type=useMemo(()=>config.jobTypes.find(item=>item.id===form.jobTypeId)??first,[config.jobTypes,first,form.jobTypeId]);
  const sites=config.sites.filter(site=>!form.customerId||site.customerId===form.customerId);
  const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(current=>({...current,[key]:value}));

  function chooseType(id:string){const next=config.jobTypes.find(item=>item.id===id);setForm(current=>({...current,jobTypeId:id,priority:next?.defaultPriority??current.priority}));}
  function validate(){
    if(step===0&&(!form.jobTypeId||!form.title.trim()))return "Choose a job type and enter what the job is.";
    if(step===1&&!form.customerId&&!form.customerName.trim())return "Choose or enter the customer.";
    if(step===1&&!form.siteId&&!form.siteAddress.trim())return "Choose or enter the site address.";
    if(step===2&&form.scheduledStart&&form.scheduledEnd&&new Date(form.scheduledEnd)<new Date(form.scheduledStart))return "The end time cannot be before the start time.";
    return "";
  }
  function next(){const problem=validate();if(problem)return setError(problem);setError("");setStep(value=>Math.min(2,value+1));}
  async function save(){const problem=validate();if(problem)return setError(problem);setSaving(true);setError("");try{await api("/jobs",{method:"POST",body:JSON.stringify({jobTypeId:form.jobTypeId,title:form.title,description:form.description||undefined,priority:form.priority,source:"OFFICE",customerId:form.customerId||undefined,customerName:form.customerId?undefined:form.customerName,siteId:form.siteId||undefined,siteName:form.siteId?undefined:form.siteName,siteAddress:form.siteId?undefined:form.siteAddress,sitePostcode:form.sitePostcode||undefined,contactName:form.contactName||undefined,contactPhone:form.contactPhone||undefined,contactEmail:form.contactEmail||undefined,accessNotes:form.accessNotes||undefined,scheduledStart:form.scheduledStart||undefined,scheduledEnd:form.scheduledEnd||undefined,personIds:form.personIds,vehicleId:form.vehicleId||undefined,purchaseOrderNumber:form.purchaseOrderNumber||undefined,reference:form.reference||undefined,customFields:{}})});onComplete();}catch(reason){setError(reason instanceof Error?reason.message:"Could not create the job.");}finally{setSaving(false);}}

  return <section className="panel job-wizard">
    <div className="job-wizard-head"><div><p className="eyebrow">New job</p><h2>Create job</h2><p className="subtle">Enter only what the office knows now. The selected job type builds the field report automatically.</p></div><BriefcaseBusiness/></div>
    <div className="job-steps">{steps.map((name,index)=><button key={name} type="button" className={index===step?"active":index<step?"done":""} onClick={()=>index<step&&setStep(index)}><span>{index+1}</span>{name}</button>)}</div>
    <div className="job-wizard-body">{error&&<p role="alert" className="form-message error">{error}</p>}
      {step===0&&<><div className="job-type-picker">{config.jobTypes.map(item=><button type="button" key={item.id} className={form.jobTypeId===item.id?"selected":""} style={{"--job-colour":item.colour} as React.CSSProperties} onClick={()=>chooseType(item.id)}><strong>{item.name}</strong><span>{item.trade}</span><small>{item.description}</small></button>)}</div><div className="form-grid"><label>What is the job? *<input autoFocus value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Blocked drain, delivery, service, repair…"/></label><label>Priority<select value={form.priority} onChange={e=>set("priority",e.target.value)}>{["LOW","NORMAL","HIGH","URGENT","EMERGENCY"].map(value=><option key={value}>{label(value)}</option>)}</select></label></div><label>Details / instructions<textarea rows={4} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Only add what the driver needs to know"/></label><details><summary>Optional references</summary><div className="form-grid"><label>Your reference<input value={form.reference} onChange={e=>set("reference",e.target.value)} placeholder="Auto-generated if blank"/></label><label>Customer PO<input value={form.purchaseOrderNumber} onChange={e=>set("purchaseOrderNumber",e.target.value)}/></label></div></details></>}
      {step===1&&<><div className="field-flow-title"><MapPin/><div><small>Where</small><h3>Customer & site</h3></div></div><div className="form-grid"><label>Existing customer<select value={form.customerId} onChange={e=>setForm(current=>({...current,customerId:e.target.value,siteId:""}))}><option value="">New / type customer</option>{config.customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label>{!form.customerId&&<label>Customer name *<input value={form.customerName} onChange={e=>set("customerName",e.target.value)}/></label>}<label>Existing site<select value={form.siteId} onChange={e=>set("siteId",e.target.value)}><option value="">New / type site</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name} · {site.postcode}</option>)}</select></label>{!form.siteId&&<><label>Site name<input value={form.siteName} onChange={e=>set("siteName",e.target.value)}/></label><label>Postcode<input value={form.sitePostcode} onChange={e=>set("sitePostcode",e.target.value)}/></label></>}</div>{!form.siteId&&<label>Address *<textarea rows={3} value={form.siteAddress} onChange={e=>set("siteAddress",e.target.value)}/></label>}<details><summary>Contact / access details</summary><div className="form-grid"><label>Contact name<input value={form.contactName} onChange={e=>set("contactName",e.target.value)}/></label><label>Phone<input value={form.contactPhone} onChange={e=>set("contactPhone",e.target.value)}/></label><label>Email<input type="email" value={form.contactEmail} onChange={e=>set("contactEmail",e.target.value)}/></label></div><label>Access / parking / permit notes<textarea rows={3} value={form.accessNotes} onChange={e=>set("accessNotes",e.target.value)}/></label></details></>}
      {step===2&&<><div className="field-flow-title"><Users/><div><small>Who / when</small><h3>Schedule & assign</h3></div></div><div className="form-grid"><label>Start<input type="datetime-local" value={form.scheduledStart} onChange={e=>set("scheduledStart",e.target.value)}/></label><label>End<input type="datetime-local" min={form.scheduledStart||undefined} value={form.scheduledEnd} onChange={e=>set("scheduledEnd",e.target.value)}/></label><label>Vehicle / plant<select value={form.vehicleId} onChange={e=>set("vehicleId",e.target.value)}><option value="">None</option>{config.vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.registration} · {vehicle.type}</option>)}</select></label></div><div><h3>Assign staff</h3><p className="subtle">Assigned staff see the job in their Driver app automatically.</p><div className="people-picker">{config.people.length?config.people.map(person=><label key={person.id}><input type="checkbox" checked={form.personIds.includes(person.id)} onChange={e=>set("personIds",e.target.checked?[...form.personIds,person.id]:form.personIds.filter(id=>id!==person.id))}/><span><strong>{person.firstName} {person.lastName}</strong><small>{label(person.personType)}</small></span></label>):<p className="subtle">Add staff first to assign this job.</p>}</div></div><section className="job-requirements"><span><Check/> {type?.formSchema.filter(field=>field.required).length??0} required report fields</span><span><Check/> {type?.riskAssessmentRequired?"Point-of-work check":"No forced risk sign-off"}</span><span><Check/> {type?.customerSignatureRequired?"Customer sign-off":"No forced signature"}</span></section><p className="subtle">The driver only sees the report fields for <strong>{type?.name}</strong>.</p></>}
      <div className="wizard-actions"><button type="button" className="secondary-button" disabled={saving} onClick={step===0?onCancel:()=>{setError("");setStep(value=>value-1);}}><ArrowLeft/> {step===0?"Cancel":"Back"}</button>{step<2?<button type="button" className="primary-button" onClick={next}>Next <ArrowRight/></button>:<button type="button" className="primary-button" disabled={saving} onClick={()=>void save()}><Check/> {saving?"Creating…":"Create job"}</button>}</div>
    </div>
  </section>;
}
