import { useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";

type Transaction={id:string;type:string;status:string;reference:string|null;counterparty:string|null;description:string|null;netPence:number;vatPence:number;grossPence:number;occurredAt:string};
type Handover={generatedAt:string;currency:string;summary:Array<{type:string;count:number;netPence:number;vatPence:number;grossPence:number}>};
const types=["QUOTE","SALES_INVOICE","PURCHASE_ORDER","SUPPLIER_INVOICE","EXPENSE","CREDIT_NOTE","PAYMENT","FUEL_COST","WORKSHOP_COST"];
const money=(p:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(p/100);

export function AccountsPage() {
  const [rows,setRows]=useState<Transaction[]>([]); const [handover,setHandover]=useState<Handover|null>(null); const [message,setMessage]=useState("");
  const [type,setType]=useState("SALES_INVOICE"); const [reference,setReference]=useState(""); const [counterparty,setCounterparty]=useState(""); const [net,setNet]=useState(""); const [vat,setVat]=useState("");
  async function load(){const [tx,h]=await Promise.all([api<Transaction[]>("/accounts/transactions"),api<Handover>("/accounts/handover")]);setRows(tx);setHandover(h);}
  useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Could not load accounts"));},[]);
  const totals=useMemo(()=>rows.reduce((a,r)=>({net:a.net+r.netPence,vat:a.vat+r.vatPence,gross:a.gross+r.grossPence}),{net:0,vat:0,gross:0}),[rows]);
  async function create(event:React.FormEvent){event.preventDefault();setMessage("");const netPence=Math.round(Number(net)*100),vatPence=Math.round(Number(vat)*100);try{await api("/accounts/transactions",{method:"POST",body:JSON.stringify({type,status:"DRAFT",reference:reference||undefined,counterparty:counterparty||undefined,netPence,vatPence,grossPence:netPence+vatPence})});setReference("");setCounterparty("");setNet("");setVat("");setMessage("Transaction saved");await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not save transaction");}}
  return <div className="page-shell">
    <div className="page-heading"><div><p className="eyebrow">Operational accounts</p><h1>Accounts</h1><p>Capture day-to-day commercial records in FleetOS and prepare a clean handover to the accounts team.</p></div></div>
    <div className="stat-grid"><article className="stat-card"><span>Net recorded</span><strong>{money(totals.net)}</strong></article><article className="stat-card"><span>VAT recorded</span><strong>{money(totals.vat)}</strong></article><article className="stat-card"><span>Gross recorded</span><strong>{money(totals.gross)}</strong></article><article className="stat-card"><span>Transactions</span><strong>{rows.length}</strong></article></div>
    <section className="dashboard-section"><p className="eyebrow">New record</p><h2>Add operational transaction</h2><form onSubmit={create} className="form-grid"><label>Type<select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="INV-1001"/></label><label>Customer / supplier<input value={counterparty} onChange={e=>setCounterparty(e.target.value)}/></label><label>Net £<input required inputMode="decimal" value={net} onChange={e=>setNet(e.target.value)}/></label><label>VAT £<input required inputMode="decimal" value={vat} onChange={e=>setVat(e.target.value)}/></label><div><button className="primary-button" type="submit">Save record</button></div></form>{message&&<p>{message}</p>}</section>
    <section className="dashboard-section"><p className="eyebrow">Ledger</p><h2>Recent records</h2>{rows.length===0?<p>No operational account records yet.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Date</th><th align="left">Type</th><th align="left">Reference</th><th align="left">Counterparty</th><th align="right">Net</th><th align="right">VAT</th><th align="right">Gross</th><th align="left">Status</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.id}><td>{new Date(r.occurredAt).toLocaleDateString("en-GB")}</td><td>{r.type}</td><td>{r.reference??"—"}</td><td>{r.counterparty??"—"}</td><td align="right">{money(r.netPence)}</td><td align="right">{money(r.vatPence)}</td><td align="right">{money(r.grossPence)}</td><td>{r.status}</td></tr>)}</tbody></table></div>}</section>
    <section className="dashboard-section"><p className="eyebrow">Accounts handover</p><h2>Accountant-ready totals</h2>{handover?.summary.length?<div className="action-grid">{handover.summary.map(r=><article className="action-card" key={r.type}><strong>{r.type}</strong><span>{r.count} records · {money(r.grossPence)} gross · {money(r.vatPence)} VAT</span></article>)}</div>:<p>Handover totals will appear as records are added.</p>}<p>This remains an operational finance layer; final reconciliation, statutory accounts and HMRC-facing submissions stay with the accounting system or accounts team.</p></section>
  </div>;
}
