import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarClock, ClipboardCheck, Plus, TriangleAlert, Wrench } from "lucide-react";
import { api } from "../../lib/api";

type Vehicle={id:string;registration:string;depotId:string|null;depotName:string|null};
type Depot={id:string;name:string;isActive:boolean};
type Defect={id:string;title:string;description:string|null;severity:string|null;status:"OPEN"|"IN_PROGRESS"|"RESOLVED";createdAt:string;vehicle:{id:string;registration:string}|null;reportedBy:{firstName:string;lastName:string}|null};
type Plan={id:string;vehicleId:string;depotId:string|null;title:string;category:string;intervalWeeks:number;nextDueAt:string;lastCompletedAt:string|null;nextDueMileage:number|null;notes:string|null;isActive:boolean;registration:string;depotName:string|null};
type WorkOrder={id:string;vehicleId:string;depotId:string|null;planId:string|null;defectId:string|null;title:string;category:string;status:string;priority:string;description:string|null;scheduledFor:string|null;dueAt:string|null;assignedTo:string|null;supplier:string|null;completionNotes:string|null;costPence:number|null;odometer:number|null;completedAt:string|null;registration:string;depotName:string|null};
type MaintenanceData={plans:Plan[];workOrders:WorkOrder[];summary:{overdue:number;dueSoon:number;openWork:number;vehicleOffRoad:number}};
type Tab="schedule"|"orders"|"defects";

const blankPlan={vehicleId:"",depotId:"",title:"Preventive maintenance inspection",category:"PMI",intervalWeeks:"6",nextDueAt:"",nextDueMileage:"",notes:""};
const blankOrder={vehicleId:"",depotId:"",planId:"",defectId:"",title:"",category:"REPAIR",priority:"ROUTINE",scheduledFor:"",dueAt:"",assignedTo:"",supplier:"",description:""};
const dateOnly=(value:string|null)=>value?new Date(value).toLocaleDateString("en-GB"):"Not set";
const label=(value:string)=>value.replaceAll("_"," ");

export function WorkshopPage(){
  const [tab,setTab]=useState<Tab>("schedule");
  const [maintenance,setMaintenance]=useState<MaintenanceData>({plans:[],workOrders:[],summary:{overdue:0,dueSoon:0,openWork:0,vehicleOffRoad:0}});
  const [defects,setDefects]=useState<Defect[]>([]); const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [depots,setDepots]=useState<Depot[]>([]);
  const [plan,setPlan]=useState(blankPlan); const [order,setOrder]=useState(blankOrder); const [showPlan,setShowPlan]=useState(false); const [showOrder,setShowOrder]=useState(false);
  const [error,setError]=useState(""); const [busy,setBusy]=useState("");
  async function load(){try{const [m,d,v,p]=await Promise.all([api<MaintenanceData>("/operations/maintenance"),api<Defect[]>("/operations/defects"),api<Vehicle[]>("/operations/vehicles/available"),api<Depot[]>("/organisation/depots")]);setMaintenance(m);setDefects(d);setVehicles(v);setDepots(p.filter(x=>x.isActive));setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load workshop records");}}
  useEffect(()=>{void load();},[]);
  const openDefects=useMemo(()=>defects.filter(d=>d.status!=="RESOLVED"),[defects]);
  const activeOrders=useMemo(()=>maintenance.workOrders.filter(w=>!["COMPLETED","CANCELLED"].includes(w.status)),[maintenance.workOrders]);

  function chooseVehicle(vehicleId:string,setter:(next:typeof blankPlan)=>void,current:typeof blankPlan){const vehicle=vehicles.find(v=>v.id===vehicleId);setter({...current,vehicleId,depotId:vehicle?.depotId||""});}
  function chooseOrderVehicle(vehicleId:string){const vehicle=vehicles.find(v=>v.id===vehicleId);setOrder(v=>({...v,vehicleId,depotId:vehicle?.depotId||""}));}
  async function createPlan(e:FormEvent){e.preventDefault();setBusy("plan");setError("");try{await api("/operations/maintenance/plans",{method:"POST",body:JSON.stringify({...plan,intervalWeeks:Number(plan.intervalWeeks),nextDueMileage:plan.nextDueMileage?Number(plan.nextDueMileage):undefined})});setPlan(blankPlan);setShowPlan(false);await load();}catch(err){setError(err instanceof Error?err.message:"Could not create maintenance plan");}finally{setBusy("");}}
  async function createOrder(e:FormEvent){e.preventDefault();setBusy("order");setError("");try{await api("/operations/maintenance/work-orders",{method:"POST",body:JSON.stringify({...order,depotId:order.depotId||undefined,planId:order.planId||undefined,defectId:order.defectId||undefined,scheduledFor:order.scheduledFor||undefined,dueAt:order.dueAt||undefined})});setOrder(blankOrder);setShowOrder(false);await load();}catch(err){setError(err instanceof Error?err.message:"Could not create work order");}finally{setBusy("");}}
  async function moveOrder(item:WorkOrder,status:string){setBusy(item.id);setError("");let completionNotes:string|null|undefined;if(status==="COMPLETED"){completionNotes=window.prompt("Completion notes / work carried out:",item.completionNotes||"");if(completionNotes===null){setBusy("");return;}}try{await api(`/operations/maintenance/work-orders/${item.id}`,{method:"PATCH",body:JSON.stringify({status,completionNotes})});await load();}catch(err){setError(err instanceof Error?err.message:"Could not update work order");}finally{setBusy("");}}
  async function moveDefect(id:string,status:Defect["status"]){setBusy(id);try{await api(`/operations/defects/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load();}catch(e){setError(e instanceof Error?e.message:"Could not update defect");}finally{setBusy("");}}
  function orderFromDefect(defect:Defect){setTab("orders");setShowOrder(true);setOrder({...blankOrder,vehicleId:defect.vehicle?.id||"",depotId:vehicles.find(v=>v.id===defect.vehicle?.id)?.depotId||"",defectId:defect.id,title:defect.title,category:"DEFECT",priority:defect.severity==="CRITICAL"?"VEHICLE_OFF_ROAD":"URGENT",description:defect.description||""});}

  return <section className="page">
    <div className="page-heading"><div><p className="eyebrow">Workshop & PMI</p><h1>Maintenance control</h1><p className="subtle">Plan inspections, manage repairs, control vehicle-off-road work and keep one evidence trail.</p></div><div className="presence">{maintenance.summary.openWork} open work orders</div></div>
    {error&&<p role="alert" className="form-message error">{error}</p>}
    <div className="metric-grid">
      <div className="metric-card"><div className="metric-icon red"><TriangleAlert size={20}/></div><div><p>PMI overdue</p><strong>{maintenance.summary.overdue}</strong><small>Requires workshop review</small></div></div>
      <div className="metric-card"><div className="metric-icon orange"><CalendarClock size={20}/></div><div><p>Due in 28 days</p><strong>{maintenance.summary.dueSoon}</strong><small>Upcoming planned maintenance</small></div></div>
      <div className="metric-card"><div className="metric-icon blue"><Wrench size={20}/></div><div><p>Open work</p><strong>{maintenance.summary.openWork}</strong><small>All active orders</small></div></div>
      <div className="metric-card"><div className="metric-icon violet"><ClipboardCheck size={20}/></div><div><p>Vehicle off road</p><strong>{maintenance.summary.vehicleOffRoad}</strong><small>Highest priority</small></div></div>
    </div>
    <div style={{display:"flex",gap:8,marginBottom:18,flexWrap:"wrap"}}>
      {(["schedule","orders","defects"] as Tab[]).map(value=><button key={value} type="button" className={tab===value?"primary-button":"secondary-button"} onClick={()=>setTab(value)}>{value==="schedule"?"PMI & schedules":value==="orders"?`Work orders (${activeOrders.length})`:`Defects (${openDefects.length})`}</button>)}
    </div>

    {tab==="schedule"&&<>
      <div style={{display:"flex",justifyContent:"flex-end",marginBottom:12}}><button className="primary-button" onClick={()=>setShowPlan(v=>!v)}><Plus size={17}/> New maintenance plan</button></div>
      {showPlan&&<form className="panel" onSubmit={createPlan} style={{padding:18,marginBottom:18}}><h2>Create recurring plan</h2><div className="form-grid" style={{marginTop:14}}>
        <label>Vehicle *<select required value={plan.vehicleId} onChange={e=>chooseVehicle(e.target.value,setPlan,plan)}><option value="">Choose vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registration}</option>)}</select></label>
        <label>Depot / site<select value={plan.depotId} onChange={e=>setPlan({...plan,depotId:e.target.value})}><option value="">No depot</option>{depots.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
        <label>Plan name *<input required value={plan.title} onChange={e=>setPlan({...plan,title:e.target.value})}/></label>
        <label>Type<select value={plan.category} onChange={e=>setPlan({...plan,category:e.target.value})}>{["PMI","SERVICE","MOT_PREP","TACHO","TYRES","OTHER"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
        <label>Repeat every (weeks) *<input required type="number" min="1" max="104" value={plan.intervalWeeks} onChange={e=>setPlan({...plan,intervalWeeks:e.target.value})}/></label>
        <label>Next due *<input required type="date" value={plan.nextDueAt} onChange={e=>setPlan({...plan,nextDueAt:e.target.value})}/></label>
        <label>Next due mileage<input type="number" min="0" value={plan.nextDueMileage} onChange={e=>setPlan({...plan,nextDueMileage:e.target.value})}/></label>
        <label style={{gridColumn:"1/-1"}}>Notes<textarea rows={3} value={plan.notes} onChange={e=>setPlan({...plan,notes:e.target.value})}/></label>
      </div><div style={{display:"flex",gap:8}}><button className="primary-button" disabled={busy==="plan"}>{busy==="plan"?"Saving…":"Create plan"}</button><button type="button" className="secondary-button" onClick={()=>setShowPlan(false)}>Cancel</button></div></form>}
      <div style={{display:"grid",gap:12}}>{maintenance.plans.map(p=>{const due=new Date(p.nextDueAt);const overdue=p.isActive&&due.getTime()<Date.now();return <article className="panel" key={p.id} style={{padding:16,opacity:p.isActive?1:.6,borderColor:overdue?"#dc2626":undefined}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"start"}}><div><p className="eyebrow">{p.registration} · {label(p.category)}{p.depotName?` · ${p.depotName}`:""}</p><h2>{p.title}</h2><p className="subtle">Every {p.intervalWeeks} weeks · next due <strong>{dateOnly(p.nextDueAt)}</strong>{p.nextDueMileage!=null?` or ${p.nextDueMileage.toLocaleString()} miles`:""}</p><small>{p.lastCompletedAt?`Last completed ${dateOnly(p.lastCompletedAt)}`:"Not completed in FleetOS yet"}</small></div><span className={`status ${overdue?"warning":"success"}`}>{overdue?"OVERDUE":p.isActive?"ACTIVE":"ARCHIVED"}</span></div><div style={{marginTop:12}}><button className="secondary-button" onClick={()=>{setTab("orders");setShowOrder(true);setOrder({...blankOrder,vehicleId:p.vehicleId,depotId:p.depotId||"",planId:p.id,title:p.title,category:p.category,priority:overdue?"URGENT":"ROUTINE",dueAt:p.nextDueAt.slice(0,10)});}}>Create work order</button></div></article>;})}{!maintenance.plans.length&&<div className="panel empty-state"><h2>No maintenance plans yet</h2><p>Add each vehicle’s PMI or service interval once. FleetOS will roll the next due date forward when work is completed.</p></div>}</div>
    </>}

    {tab==="orders"&&<>
      <div style={{display:"flex",justifyContent:"flex-end",marginBottom:12}}><button className="primary-button" onClick={()=>setShowOrder(v=>!v)}><Plus size={17}/> New work order</button></div>
      {showOrder&&<form className="panel" onSubmit={createOrder} style={{padding:18,marginBottom:18}}><h2>Create workshop work order</h2><div className="form-grid" style={{marginTop:14}}>
        <label>Vehicle *<select required value={order.vehicleId} onChange={e=>chooseOrderVehicle(e.target.value)}><option value="">Choose vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registration}</option>)}</select></label>
        <label>Depot / site<select value={order.depotId} onChange={e=>setOrder({...order,depotId:e.target.value})}><option value="">No depot</option>{depots.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
        <label>Title *<input required value={order.title} onChange={e=>setOrder({...order,title:e.target.value})}/></label>
        <label>Type<select value={order.category} onChange={e=>setOrder({...order,category:e.target.value})}>{["PMI","SERVICE","MOT_PREP","TACHO","TYRES","DEFECT","REPAIR","OTHER"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
        <label>Priority<select value={order.priority} onChange={e=>setOrder({...order,priority:e.target.value})}>{["ROUTINE","URGENT","VEHICLE_OFF_ROAD"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
        <label>Linked plan<select value={order.planId} onChange={e=>setOrder({...order,planId:e.target.value})}><option value="">No recurring plan</option>{maintenance.plans.filter(p=>p.vehicleId===order.vehicleId).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>
        <label>Scheduled for<input type="date" value={order.scheduledFor} onChange={e=>setOrder({...order,scheduledFor:e.target.value})}/></label>
        <label>Due by<input type="date" value={order.dueAt} onChange={e=>setOrder({...order,dueAt:e.target.value})}/></label>
        <label>Assigned to<input value={order.assignedTo} onChange={e=>setOrder({...order,assignedTo:e.target.value})} placeholder="Technician or team"/></label>
        <label>Supplier / garage<input value={order.supplier} onChange={e=>setOrder({...order,supplier:e.target.value})}/></label>
        <label style={{gridColumn:"1/-1"}}>Work required<textarea rows={3} value={order.description} onChange={e=>setOrder({...order,description:e.target.value})}/></label>
      </div><div style={{display:"flex",gap:8}}><button className="primary-button" disabled={busy==="order"}>{busy==="order"?"Saving…":"Create work order"}</button><button type="button" className="secondary-button" onClick={()=>setShowOrder(false)}>Cancel</button></div></form>}
      <div style={{display:"grid",gap:12}}>{maintenance.workOrders.map(w=><article className="panel" key={w.id} style={{padding:16,opacity:["COMPLETED","CANCELLED"].includes(w.status)?.62:1,borderColor:w.priority==="VEHICLE_OFF_ROAD"?"#dc2626":undefined}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"start"}}><div><p className="eyebrow">{w.registration} · {label(w.category)}{w.depotName?` · ${w.depotName}`:""}</p><h2>{w.title}</h2><p className="subtle">{w.description||"No work description"}</p><small>{w.dueAt?`Due ${dateOnly(w.dueAt)}`:"No due date"}{w.assignedTo?` · Assigned ${w.assignedTo}`:""}{w.supplier?` · ${w.supplier}`:""}</small>{w.completionNotes&&<p><strong>Completed:</strong> {w.completionNotes}</p>}</div><div style={{textAlign:"right"}}><span className={`status ${w.status==="COMPLETED"?"success":"warning"}`}>{label(w.status)}</span><p className="subtle">{label(w.priority)}</p></div></div>{!["COMPLETED","CANCELLED"].includes(w.status)&&<div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap"}}>{w.status==="PLANNED"&&<button className="secondary-button" disabled={busy===w.id} onClick={()=>void moveOrder(w,"BOOKED")}>Book in</button>}{w.status!=="IN_PROGRESS"&&<button className="primary-button" disabled={busy===w.id} onClick={()=>void moveOrder(w,"IN_PROGRESS")}>Start work</button>}<button className="secondary-button" disabled={busy===w.id} onClick={()=>void moveOrder(w,"WAITING_PARTS")}>Waiting parts</button><button className="primary-button" disabled={busy===w.id} onClick={()=>void moveOrder(w,"COMPLETED")}>Complete</button></div>}</article>)}{!maintenance.workOrders.length&&<div className="panel empty-state"><h2>No work orders</h2><p>Create planned maintenance work or turn a driver defect into a workshop order.</p></div>}</div>
    </>}

    {tab==="defects"&&<div style={{display:"grid",gap:12}}>{defects.map(d=><article className="panel" key={d.id} style={{padding:16,opacity:d.status==="RESOLVED"?.65:1}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start"}}><div><p className="eyebrow">{d.vehicle?.registration||"No vehicle"} · {d.severity||"MEDIUM"}</p><h2>{d.title}</h2><p className="subtle">{d.description||"No extra details"}</p><small>Reported {new Date(d.createdAt).toLocaleString("en-GB")} {d.reportedBy?`by ${d.reportedBy.firstName} ${d.reportedBy.lastName}`:""}</small></div><strong>{label(d.status)}</strong></div><div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap"}}>{d.status==="OPEN"&&<button disabled={busy===d.id} className="secondary-button" onClick={()=>void moveDefect(d.id,"IN_PROGRESS")}>Accept repair</button>}{d.status!=="RESOLVED"&&d.vehicle&&<button className="primary-button" onClick={()=>orderFromDefect(d)}>Create work order</button>}{d.status!=="RESOLVED"&&<button disabled={busy===d.id} className="secondary-button" onClick={()=>void moveDefect(d.id,"RESOLVED")}>Resolve without order</button>}{d.status==="RESOLVED"&&<button disabled={busy===d.id} className="secondary-button" onClick={()=>void moveDefect(d.id,"OPEN")}>Reopen</button>}</div></article>)}{!defects.length&&<div className="panel empty-state"><h2>No defects in the queue</h2><p>Driver-reported defects will appear here automatically.</p></div>}</div>}
  </section>;
}
