import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { loadLocalAccessibilityPreferences, type AccessibilityPreferences } from "./accessibility";

export type Language = AccessibilityPreferences["language"];
type Messages = Record<string, string>;

const en: Messages = {
  "nav.today":"Today","nav.tacho":"My Tacho","nav.work":"My Work","nav.messages":"Messages","nav.settings":"Settings",
  "shell.openNav":"Open navigation","shell.closeNav":"Close navigation","shell.company":"Company workspace","shell.addCompany":"Add company","shell.companyPrompt":"Company / fleet name","shell.notifications":"Notifications","shell.alerts":"Fleet alerts","shell.allClear":"All clear","shell.noAlerts":"No active alerts for your role.","shell.companySettings":"Company settings","shell.accessibility":"Accessibility & language","shell.signOut":"Sign out","shell.accessDenied":"Access denied","shell.accessDeniedDetail":"This area is not available from this FleetOS entry point.","shell.return":"Return",
  "prefs.eyebrow":"Your preferences","prefs.title":"Accessibility & language","prefs.intro":"These choices belong to your user account and apply across FleetOS as soon as you change them.","prefs.language":"Preferred interface language","prefs.translationReady":"FleetOS interface text uses shared translation packs with English fallback. User-entered messages, evidence and audit records always keep their original wording.","prefs.largeText":"Large text","prefs.largeControls":"Large controls","prefs.highContrast":"High contrast","prefs.reducedMotion":"Reduced motion","prefs.easyRead":"Easy Read","prefs.darkMode":"Dark / night mode","prefs.readAloud":"Read aloud preference","prefs.voiceInput":"Voice input preference","common.on":"On","common.off":"Off",
  "driver.brand":"FleetOS Driver","driver.today":"Today","driver.mobileWorkforce":"Mobile workforce","driver.myWork":"My work","driver.workIntro":"Appointments, site details, job sheets and safety controls sent directly from the office.","driver.refresh":"Refresh jobs","driver.loading":"Loading assigned work…","driver.noWork":"No work assigned","driver.noWorkDetail":"Jobs allocated to your staff record will appear here.","driver.appointment":"Appointment","driver.site":"Site","driver.team":"Team","driver.you":"You","driver.openWork":"Open work order","driver.awaitingSchedule":"Awaiting schedule"
};

const packs: Record<Language, Messages> = {
  en,
  pl:{"nav.today":"Dzisiaj","nav.tacho":"Mój tachograf","nav.work":"Moja praca","nav.messages":"Wiadomości","nav.settings":"Ustawienia","shell.openNav":"Otwórz nawigację","shell.closeNav":"Zamknij nawigację","shell.company":"Firma","shell.addCompany":"Dodaj firmę","shell.notifications":"Powiadomienia","shell.alerts":"Alerty floty","shell.allClear":"Wszystko w porządku","shell.noAlerts":"Brak aktywnych alertów dla Twojej roli.","shell.companySettings":"Ustawienia firmy","shell.accessibility":"Dostępność i język","shell.signOut":"Wyloguj się","shell.accessDenied":"Brak dostępu","shell.return":"Wróć","prefs.eyebrow":"Twoje preferencje","prefs.title":"Dostępność i język","prefs.language":"Preferowany język interfejsu","common.on":"Wł.","common.off":"Wył.","driver.brand":"Kierowca FleetOS","driver.today":"Dzisiaj","driver.mobileWorkforce":"Praca mobilna","driver.myWork":"Moja praca","driver.refresh":"Odśwież zlecenia","driver.loading":"Ładowanie przydzielonej pracy…","driver.noWork":"Brak przydzielonej pracy","driver.appointment":"Termin","driver.site":"Miejsce","driver.team":"Zespół","driver.you":"Ty","driver.openWork":"Otwórz zlecenie","driver.awaitingSchedule":"Oczekuje na termin"},
  ro:{"nav.today":"Astăzi","nav.tacho":"Tahograful meu","nav.work":"Munca mea","nav.messages":"Mesaje","nav.settings":"Setări","shell.openNav":"Deschide navigarea","shell.closeNav":"Închide navigarea","shell.notifications":"Notificări","shell.alerts":"Alerte flotă","shell.allClear":"Totul este în regulă","shell.accessibility":"Accesibilitate și limbă","shell.signOut":"Deconectare","shell.accessDenied":"Acces refuzat","shell.return":"Înapoi","prefs.eyebrow":"Preferințele tale","prefs.title":"Accesibilitate și limbă","prefs.language":"Limba preferată a interfeței","common.on":"Pornit","common.off":"Oprit","driver.brand":"Șofer FleetOS","driver.today":"Astăzi","driver.mobileWorkforce":"Echipă mobilă","driver.myWork":"Munca mea","driver.refresh":"Actualizează lucrările","driver.loading":"Se încarcă lucrările…","driver.noWork":"Nicio lucrare alocată","driver.appointment":"Programare","driver.site":"Locație","driver.team":"Echipă","driver.you":"Tu","driver.openWork":"Deschide comanda","driver.awaitingSchedule":"În așteptarea programării"},
  lt:{"nav.today":"Šiandien","nav.tacho":"Mano tachografas","nav.work":"Mano darbai","nav.messages":"Žinutės","nav.settings":"Nustatymai","shell.notifications":"Pranešimai","shell.alerts":"Parko įspėjimai","shell.allClear":"Viskas gerai","shell.accessibility":"Prieinamumas ir kalba","shell.signOut":"Atsijungti","shell.accessDenied":"Prieiga uždrausta","shell.return":"Grįžti","prefs.eyebrow":"Jūsų nuostatos","prefs.title":"Prieinamumas ir kalba","prefs.language":"Pageidaujama sąsajos kalba","common.on":"Įjungta","common.off":"Išjungta","driver.brand":"FleetOS vairuotojas","driver.today":"Šiandien","driver.mobileWorkforce":"Mobilus darbas","driver.myWork":"Mano darbai","driver.refresh":"Atnaujinti darbus","driver.loading":"Įkeliami darbai…","driver.noWork":"Darbų nepriskirta","driver.appointment":"Laikas","driver.site":"Vieta","driver.team":"Komanda","driver.you":"Jūs","driver.openWork":"Atverti užsakymą","driver.awaitingSchedule":"Laukiama grafiko"},
  bg:{"nav.today":"Днес","nav.tacho":"Моят тахограф","nav.work":"Моята работа","nav.messages":"Съобщения","nav.settings":"Настройки","shell.notifications":"Известия","shell.alerts":"Сигнали за автопарка","shell.allClear":"Всичко е наред","shell.accessibility":"Достъпност и език","shell.signOut":"Изход","shell.accessDenied":"Достъпът е отказан","shell.return":"Назад","prefs.eyebrow":"Вашите предпочитания","prefs.title":"Достъпност и език","prefs.language":"Предпочитан език на интерфейса","common.on":"Вкл.","common.off":"Изкл.","driver.brand":"FleetOS шофьор","driver.today":"Днес","driver.mobileWorkforce":"Мобилна работа","driver.myWork":"Моята работа","driver.refresh":"Обнови задачите","driver.loading":"Зареждане на задачите…","driver.noWork":"Няма възложена работа","driver.appointment":"Час","driver.site":"Обект","driver.team":"Екип","driver.you":"Вие","driver.openWork":"Отвори поръчката","driver.awaitingSchedule":"Очаква график"},
  uk:{"nav.today":"Сьогодні","nav.tacho":"Мій тахограф","nav.work":"Моя робота","nav.messages":"Повідомлення","nav.settings":"Налаштування","shell.notifications":"Сповіщення","shell.alerts":"Сповіщення автопарку","shell.allClear":"Усе гаразд","shell.accessibility":"Доступність і мова","shell.signOut":"Вийти","shell.accessDenied":"Доступ заборонено","shell.return":"Назад","prefs.eyebrow":"Ваші налаштування","prefs.title":"Доступність і мова","prefs.language":"Бажана мова інтерфейсу","common.on":"Увімк.","common.off":"Вимк.","driver.brand":"Водій FleetOS","driver.today":"Сьогодні","driver.mobileWorkforce":"Мобільна робота","driver.myWork":"Моя робота","driver.refresh":"Оновити завдання","driver.loading":"Завантаження завдань…","driver.noWork":"Немає призначеної роботи","driver.appointment":"Час","driver.site":"Місце","driver.team":"Команда","driver.you":"Ви","driver.openWork":"Відкрити замовлення","driver.awaitingSchedule":"Очікує розкладу"},
  pt:{"nav.today":"Hoje","nav.tacho":"Meu tacógrafo","nav.work":"Meu trabalho","nav.messages":"Mensagens","nav.settings":"Definições","shell.notifications":"Notificações","shell.alerts":"Alertas da frota","shell.allClear":"Tudo em ordem","shell.accessibility":"Acessibilidade e idioma","shell.signOut":"Terminar sessão","shell.accessDenied":"Acesso negado","shell.return":"Voltar","prefs.eyebrow":"As suas preferências","prefs.title":"Acessibilidade e idioma","prefs.language":"Idioma preferido da interface","common.on":"Ligado","common.off":"Desligado","driver.brand":"Motorista FleetOS","driver.today":"Hoje","driver.mobileWorkforce":"Trabalho móvel","driver.myWork":"Meu trabalho","driver.refresh":"Atualizar trabalhos","driver.loading":"A carregar trabalhos…","driver.noWork":"Nenhum trabalho atribuído","driver.appointment":"Marcação","driver.site":"Local","driver.team":"Equipa","driver.you":"Você","driver.openWork":"Abrir ordem","driver.awaitingSchedule":"A aguardar marcação"},
  es:{"nav.today":"Hoy","nav.tacho":"Mi tacógrafo","nav.work":"Mi trabajo","nav.messages":"Mensajes","nav.settings":"Ajustes","shell.notifications":"Notificaciones","shell.alerts":"Alertas de flota","shell.allClear":"Todo correcto","shell.accessibility":"Accesibilidad e idioma","shell.signOut":"Cerrar sesión","shell.accessDenied":"Acceso denegado","shell.return":"Volver","prefs.eyebrow":"Tus preferencias","prefs.title":"Accesibilidad e idioma","prefs.language":"Idioma preferido de la interfaz","common.on":"Sí","common.off":"No","driver.brand":"Conductor FleetOS","driver.today":"Hoy","driver.mobileWorkforce":"Trabajo móvil","driver.myWork":"Mi trabajo","driver.refresh":"Actualizar trabajos","driver.loading":"Cargando trabajos…","driver.noWork":"No hay trabajo asignado","driver.appointment":"Cita","driver.site":"Lugar","driver.team":"Equipo","driver.you":"Tú","driver.openWork":"Abrir orden","driver.awaitingSchedule":"Pendiente de programación"}
};

type I18nValue = { language: Language; t: (key: string) => string; locale: string };
const I18nContext = createContext<I18nValue>({ language:"en", t:key=>en[key] ?? key, locale:"en-GB" });
const locales: Record<Language,string> = { en:"en-GB",pl:"pl-PL",ro:"ro-RO",lt:"lt-LT",bg:"bg-BG",uk:"uk-UA",pt:"pt-PT",es:"es-ES" };

export function I18nProvider({ children }:{ children:ReactNode }) {
  const [language,setLanguage]=useState<Language>(()=>loadLocalAccessibilityPreferences().language);
  useEffect(()=>{const update=(event:Event)=>setLanguage(((event as CustomEvent<AccessibilityPreferences>).detail ?? loadLocalAccessibilityPreferences()).language);window.addEventListener("fleetos:preferences",update);window.addEventListener("storage",update);return()=>{window.removeEventListener("fleetos:preferences",update);window.removeEventListener("storage",update);};},[]);
  const value=useMemo<I18nValue>(()=>({language,locale:locales[language],t:(key)=>packs[language][key] ?? en[key] ?? key}),[language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export const useI18n=()=>useContext(I18nContext);

