import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { loadLocalAccessibilityPreferences, type AccessibilityPreferences } from "./accessibility";

export type Language = AccessibilityPreferences["language"];
type Messages = Record<string, string>;

const en: Messages = {
  "nav.today":"Today","nav.tacho":"My Tacho","nav.work":"My Work","nav.messages":"Messages","nav.settings":"Settings",
  "shell.openNav":"Open navigation","shell.closeNav":"Close navigation","shell.company":"Company workspace","shell.addCompany":"Add company","shell.companyPrompt":"Company / fleet name","shell.notifications":"Notifications","shell.alerts":"Fleet alerts","shell.allClear":"All clear","shell.noAlerts":"No active alerts for your role.","shell.companySettings":"Company settings","shell.accessibility":"Accessibility & language","shell.signOut":"Sign out","shell.accessDenied":"Access denied","shell.accessDeniedDetail":"This area is not available from this FleetOS entry point.","shell.return":"Return",
  "prefs.eyebrow":"Your preferences","prefs.title":"Accessibility & language","prefs.intro":"These choices belong to your user account and apply across FleetOS as soon as you change them.","prefs.language":"Preferred interface language","prefs.translationReady":"FleetOS interface text uses shared translation packs with English fallback. User-entered messages, evidence and audit records always keep their original wording.","prefs.largeText":"Large text","prefs.largeControls":"Large controls","prefs.highContrast":"High contrast","prefs.reducedMotion":"Reduced motion","prefs.easyRead":"Easy Read","prefs.darkMode":"Dark / night mode","prefs.readAloud":"Read aloud preference","prefs.voiceInput":"Voice input preference","common.on":"On","common.off":"Off",
  "driver.brand":"FleetOS Driver","driver.today":"Today","driver.mobileWorkforce":"Mobile workforce","driver.myWork":"My work","driver.workIntro":"Appointments, site details, job sheets and safety controls sent directly from the office.","driver.refresh":"Refresh jobs","driver.loading":"Loading assigned work…","driver.noWork":"No work assigned","driver.noWorkDetail":"Jobs allocated to your staff record will appear here.","driver.appointment":"Appointment","driver.site":"Site","driver.team":"Team","driver.you":"You","driver.openWork":"Open work order","driver.awaitingSchedule":"Awaiting schedule"
};

const packs: Record<Language, Messages> = {
  en,
  pl:{"nav.today":"Dzisiaj","nav.tacho":"Mój tachograf","nav.work":"Moja praca","nav.messages":"Wiadomości","nav.settings":"Ustawienia","shell.openNav":"Otwórz nawigację","shell.closeNav":"Zamknij nawigację","shell.company":"Firma","shell.addCompany":"Dodaj firmę","shell.notifications":"Powiadomienia","shell.alerts":"Alerty floty","shell.allClear":"Wszystko w porządku","shell.noAlerts":"Brak aktywnych alertów dla Twojej roli.","shell.companySettings":"Ustawienia firmy","shell.accessibility":"Dostępność i język","shell.signOut":"Wyloguj się","shell.accessDenied":"Brak dostępu","shell.return":"Wróć","prefs.eyebrow":"Twoje preferencje","prefs.title":"Dostępność i język","prefs.language":"Preferowany język interfejsu","common.on":"Wł.","common.off":"Wył.","driver.brand":"Kierowca FleetOS","driver.today":"Dzisiaj","driver.mobileWorkforce":"Praca mobilna","driver.myWork":"Moja praca","driver.refresh":"Odśwież zlecenia","driver.loading":"Ładowanie przydzielonej pracy…","driver.noWork":"Brak przydzielonej pracy","driver.appointment":"Termin","driver.site":"Miejsce","driver.team":"Zespół","driver.you":"Ty","driver.openWork":"Otwórz zlecenie","driver.awaitingSchedule":"Oczekuje na termin"},
  ro:{"nav.today":"Astăzi","nav.tacho":"Tahograful meu","nav.work":"Munca mea","nav.messages":"Mesaje","nav.settings":"Setări","shell.openNav":"Deschide navigarea","shell.closeNav":"Închide navigarea","shell.notifications":"Notificări","shell.alerts":"Alerte flotă","shell.allClear":"Totul este în regulă","shell.accessibility":"Accesibilitate și limbă","shell.signOut":"Deconectare","shell.accessDenied":"Acces refuzat","shell.return":"Înapoi","prefs.eyebrow":"Preferințele tale","prefs.title":"Accesibilitate și limbă","prefs.language":"Limba preferată a interfeței","common.on":"Pornit","common.off":"Oprit","driver.brand":"Șofer FleetOS","driver.today":"Astăzi","driver.mobileWorkforce":"Echipă mobilă","driver.myWork":"Munca mea","driver.refresh":"Actualizează lucrările","driver.loading":"Se încarcă lucrările…","driver.noWork":"Nicio lucrare alocată","driver.appointment":"Programare","driver.site":"Locație","driver.team":"Echipă","driver.you":"Tu","driver.openWork":"Deschide comanda","driver.awaitingSchedule":"În așteptarea programării"},
  lt:{"nav.today":"Šiandien","nav.tacho":"Mano tachografas","nav.work":"Mano darbai","nav.messages":"Žinutės","nav.settings":"Nustatymai","shell.notifications":"Pranešimai","shell.alerts":"Parko įspėjimai","shell.allClear":"Viskas gerai","shell.accessibility":"Prieinamumas ir kalba","shell.signOut":"Atsijungti","shell.accessDenied":"Prieiga uždrausta","shell.return":"Grįžti","prefs.eyebrow":"Jūsų nuostatos","prefs.title":"Prieinamumas ir kalba","prefs.language":"Pageidaujama sąsajos kalba","common.on":"Įjungta","common.off":"Išjungta","driver.brand":"FleetOS vairuotojas","driver.today":"Šiandien","driver.mobileWorkforce":"Mobilus darbas","driver.myWork":"Mano darbai","driver.refresh":"Atnaujinti darbus","driver.loading":"Įkeliami darbai…","driver.noWork":"Darbų nepriskirta","driver.appointment":"Laikas","driver.site":"Vieta","driver.team":"Komanda","driver.you":"Jūs","driver.openWork":"Atverti užsakymą","driver.awaitingSchedule":"Laukiama grafiko"},
  bg:{"nav.today":"Днес","nav.tacho":"Моят тахограф","nav.work":"Моята работа","nav.messages":"Съобщения","nav.settings":"Настройки","shell.notifications":"Известия","shell.alerts":"Сигнали за автопарка","shell.allClear":"Всичко е наред","shell.accessibility":"Достъпност и език","shell.signOut":"Изход","shell.accessDenied":"Достъпът е отказан","shell.return":"Назад","prefs.eyebrow":"Вашите предпочитания","prefs.title":"Достъпност и език","prefs.language":"Предпочитан език на интерфейса","common.on":"Вкл.","common.off":"Изкл.","driver.brand":"FleetOS шофьор","driver.today":"Днес","driver.mobileWorkforce":"Мобилна работа","driver.myWork":"Моята работа","driver.refresh":"Обнови задачите","driver.loading":"Зареждане на задачите…","driver.noWork":"Няма възложена работа","driver.appointment":"Час","driver.site":"Обект","driver.team":"Екип","driver.you":"Вие","driver.openWork":"Отвори поръчката","driver.awaitingSchedule":"Очаква график"},
  uk:{"nav.today":"Сьогодні","nav.tacho":"Мій тахограф","nav.work":"Моя робота","nav.messages":"Повідомлення","nav.settings":"Налаштування","shell.notifications":"Сповіщення","shell.alerts":"Сповіщення автопарку","shell.allClear":"Усе гаразд","shell.accessibility":"Доступність і мова","shell.signOut":"Вийти","shell.accessDenied":"Доступ заборонено","shell.return":"Назад","prefs.eyebrow":"Ваші налаштування","prefs.title":"Доступність і мова","prefs.language":"Бажана мова інтерфейсу","common.on":"Увімк.","common.off":"Вимк.","driver.brand":"Водій FleetOS","driver.today":"Сьогодні","driver.mobileWorkforce":"Мобільна робота","driver.myWork":"Моя робота","driver.refresh":"Оновити завдання","driver.loading":"Завантаження завдань…","driver.noWork":"Немає призначеної роботи","driver.appointment":"Час","driver.site":"Місце","driver.team":"Команда","driver.you":"Ви","driver.openWork":"Відкрити замовлення","driver.awaitingSchedule":"Очікує розкладу"},
  pt:{"nav.today":"Hoje","nav.tacho":"Meu tacógrafo","nav.work":"Meu trabalho","nav.messages":"Mensagens","nav.settings":"Definições","shell.notifications":"Notificações","shell.alerts":"Alertas da frota","shell.allClear":"Tudo em ordem","shell.accessibility":"Acessibilidade e idioma","shell.signOut":"Terminar sessão","shell.accessDenied":"Acesso negado","shell.return":"Voltar","prefs.eyebrow":"As suas preferências","prefs.title":"Acessibilidade e idioma","prefs.language":"Idioma preferido da interface","common.on":"Ligado","common.off":"Desligado","driver.brand":"Motorista FleetOS","driver.today":"Hoje","driver.mobileWorkforce":"Trabalho móvel","driver.myWork":"Meu trabalho","driver.refresh":"Atualizar trabalhos","driver.loading":"A carregar trabalhos…","driver.noWork":"Nenhum trabalho atribuído","driver.appointment":"Marcação","driver.site":"Local","driver.team":"Equipa","driver.you":"Você","driver.openWork":"Abrir ordem","driver.awaitingSchedule":"A aguardar marcação"},
  es:{"nav.today":"Hoy","nav.tacho":"Mi tacógrafo","nav.work":"Mi trabajo","nav.messages":"Mensajes","nav.settings":"Ajustes","shell.notifications":"Notificaciones","shell.alerts":"Alertas de flota","shell.allClear":"Todo correcto","shell.accessibility":"Accesibilidad e idioma","shell.signOut":"Cerrar sesión","shell.accessDenied":"Acceso denegado","shell.return":"Volver","prefs.eyebrow":"Tus preferencias","prefs.title":"Accesibilidad e idioma","prefs.language":"Idioma preferido de la interfaz","common.on":"Sí","common.off":"No","driver.brand":"Conductor FleetOS","driver.today":"Hoy","driver.mobileWorkforce":"Trabajo móvil","driver.myWork":"Mi trabajo","driver.refresh":"Actualizar trabajos","driver.loading":"Cargando trabajos…","driver.noWork":"No hay trabajo asignado","driver.appointment":"Cita","driver.site":"Lugar","driver.team":"Equipo","driver.you":"Tú","driver.openWork":"Abrir orden","driver.awaitingSchedule":"Pendiente de programación"}
};

const adminPacks: Record<Language, Messages> = {
  en:{"admin.yourRecords":"Your records","admin.myAdmin":"My admin","admin.requestOrSick":"Request leave or report sickness","admin.action":"What do you need to do?","admin.requestLeave":"Request leave","admin.reportSickness":"Report sickness","admin.from":"From","admin.to":"To","admin.officeInfo":"Information for the office","admin.leavePlaceholder":"Optional note about your leave request","admin.sicknessPlaceholder":"Tell the office when you became unwell and anything they need to know","admin.sending":"Sending…","admin.sendLeave":"Send leave request","admin.leaveSent":"Leave request sent to the office for approval.","admin.sicknessSent":"Sickness reported to the office.","admin.sendFailed":"Could not send this admin request.","admin.training":"Training & expiries","admin.nothingDue":"Nothing due.","admin.leaveAbsence":"Leave / absence","admin.noRequests":"No recent requests.","admin.office":"Office","admin.recentChecks":"Recent checks"},
  pl:{"admin.yourRecords":"Twoje dane","admin.myAdmin":"Moje sprawy","admin.requestOrSick":"Poproś o urlop lub zgłoś chorobę","admin.action":"Co chcesz zrobić?","admin.requestLeave":"Poproś o urlop","admin.reportSickness":"Zgłoś chorobę","admin.from":"Od","admin.to":"Do","admin.officeInfo":"Informacje dla biura","admin.leavePlaceholder":"Opcjonalna informacja o urlopie","admin.sicknessPlaceholder":"Napisz, od kiedy chorujesz i co biuro powinno wiedzieć","admin.sending":"Wysyłanie…","admin.sendLeave":"Wyślij wniosek urlopowy","admin.leaveSent":"Wniosek urlopowy wysłano do zatwierdzenia.","admin.sicknessSent":"Chorobę zgłoszono do biura.","admin.sendFailed":"Nie udało się wysłać zgłoszenia.","admin.training":"Szkolenia i terminy","admin.nothingDue":"Brak terminów.","admin.leaveAbsence":"Urlop / nieobecność","admin.noRequests":"Brak ostatnich zgłoszeń.","admin.office":"Biuro","admin.recentChecks":"Ostatnie kontrole"},
  ro:{"admin.yourRecords":"Înregistrările tale","admin.myAdmin":"Administrarea mea","admin.requestOrSick":"Solicită concediu sau raportează boala","admin.action":"Ce dorești să faci?","admin.requestLeave":"Solicită concediu","admin.reportSickness":"Raportează boala","admin.from":"De la","admin.to":"Până la","admin.officeInfo":"Informații pentru birou","admin.leavePlaceholder":"Notă opțională despre concediu","admin.sicknessPlaceholder":"Spune biroului când te-ai îmbolnăvit și ce trebuie să știe","admin.sending":"Se trimite…","admin.sendLeave":"Trimite cererea","admin.leaveSent":"Cererea de concediu a fost trimisă pentru aprobare.","admin.sicknessSent":"Boala a fost raportată biroului.","admin.sendFailed":"Cererea nu a putut fi trimisă.","admin.training":"Instruire și expirări","admin.nothingDue":"Nimic scadent.","admin.leaveAbsence":"Concediu / absență","admin.noRequests":"Nicio cerere recentă.","admin.office":"Birou","admin.recentChecks":"Verificări recente"},
  lt:{"admin.yourRecords":"Jūsų įrašai","admin.myAdmin":"Mano administravimas","admin.requestOrSick":"Prašyti atostogų arba pranešti apie ligą","admin.action":"Ką norite atlikti?","admin.requestLeave":"Prašyti atostogų","admin.reportSickness":"Pranešti apie ligą","admin.from":"Nuo","admin.to":"Iki","admin.officeInfo":"Informacija biurui","admin.leavePlaceholder":"Neprivaloma pastaba apie atostogas","admin.sicknessPlaceholder":"Nurodykite, kada susirgote ir ką biuras turi žinoti","admin.sending":"Siunčiama…","admin.sendLeave":"Siųsti prašymą","admin.leaveSent":"Atostogų prašymas išsiųstas patvirtinti.","admin.sicknessSent":"Apie ligą pranešta biurui.","admin.sendFailed":"Nepavyko išsiųsti prašymo.","admin.training":"Mokymai ir galiojimas","admin.nothingDue":"Nieko nereikia.","admin.leaveAbsence":"Atostogos / neatvykimas","admin.noRequests":"Nėra naujų prašymų.","admin.office":"Biuras","admin.recentChecks":"Naujausios patikros"},
  bg:{"admin.yourRecords":"Вашите записи","admin.myAdmin":"Моята администрация","admin.requestOrSick":"Заявете отпуск или съобщете заболяване","admin.action":"Какво искате да направите?","admin.requestLeave":"Заявете отпуск","admin.reportSickness":"Съобщете заболяване","admin.from":"От","admin.to":"До","admin.officeInfo":"Информация за офиса","admin.leavePlaceholder":"Незадължителна бележка за отпуска","admin.sicknessPlaceholder":"Кажете кога сте се разболели и какво трябва да знае офисът","admin.sending":"Изпращане…","admin.sendLeave":"Изпрати заявката","admin.leaveSent":"Заявката за отпуск е изпратена за одобрение.","admin.sicknessSent":"Заболяването е съобщено на офиса.","admin.sendFailed":"Заявката не можа да бъде изпратена.","admin.training":"Обучение и валидност","admin.nothingDue":"Няма предстоящи.","admin.leaveAbsence":"Отпуск / отсъствие","admin.noRequests":"Няма скорошни заявки.","admin.office":"Офис","admin.recentChecks":"Последни проверки"},
  uk:{"admin.yourRecords":"Ваші записи","admin.myAdmin":"Моє адміністрування","admin.requestOrSick":"Запросити відпустку або повідомити про хворобу","admin.action":"Що ви хочете зробити?","admin.requestLeave":"Запросити відпустку","admin.reportSickness":"Повідомити про хворобу","admin.from":"Від","admin.to":"До","admin.officeInfo":"Інформація для офісу","admin.leavePlaceholder":"Необов'язкова примітка про відпустку","admin.sicknessPlaceholder":"Повідомте, коли ви захворіли та що потрібно знати офісу","admin.sending":"Надсилання…","admin.sendLeave":"Надіслати запит","admin.leaveSent":"Запит на відпустку надіслано на схвалення.","admin.sicknessSent":"Про хворобу повідомлено офісу.","admin.sendFailed":"Не вдалося надіслати запит.","admin.training":"Навчання та строки","admin.nothingDue":"Нічого не очікується.","admin.leaveAbsence":"Відпустка / відсутність","admin.noRequests":"Немає нещодавніх запитів.","admin.office":"Офіс","admin.recentChecks":"Останні перевірки"},
  pt:{"admin.yourRecords":"Os seus registos","admin.myAdmin":"A minha administração","admin.requestOrSick":"Pedir férias ou comunicar doença","admin.action":"O que precisa de fazer?","admin.requestLeave":"Pedir férias","admin.reportSickness":"Comunicar doença","admin.from":"De","admin.to":"Até","admin.officeInfo":"Informação para o escritório","admin.leavePlaceholder":"Nota opcional sobre o pedido de férias","admin.sicknessPlaceholder":"Informe quando ficou doente e o que o escritório precisa de saber","admin.sending":"A enviar…","admin.sendLeave":"Enviar pedido","admin.leaveSent":"Pedido de férias enviado para aprovação.","admin.sicknessSent":"Doença comunicada ao escritório.","admin.sendFailed":"Não foi possível enviar o pedido.","admin.training":"Formação e validades","admin.nothingDue":"Nada pendente.","admin.leaveAbsence":"Férias / ausência","admin.noRequests":"Sem pedidos recentes.","admin.office":"Escritório","admin.recentChecks":"Verificações recentes"},
  es:{"admin.yourRecords":"Tus registros","admin.myAdmin":"Mi administración","admin.requestOrSick":"Solicitar permiso o comunicar enfermedad","admin.action":"¿Qué necesitas hacer?","admin.requestLeave":"Solicitar permiso","admin.reportSickness":"Comunicar enfermedad","admin.from":"Desde","admin.to":"Hasta","admin.officeInfo":"Información para la oficina","admin.leavePlaceholder":"Nota opcional sobre tu solicitud","admin.sicknessPlaceholder":"Indica cuándo enfermaste y lo que debe saber la oficina","admin.sending":"Enviando…","admin.sendLeave":"Enviar solicitud","admin.leaveSent":"Solicitud enviada a la oficina para su aprobación.","admin.sicknessSent":"Enfermedad comunicada a la oficina.","admin.sendFailed":"No se pudo enviar la solicitud.","admin.training":"Formación y caducidades","admin.nothingDue":"Nada pendiente.","admin.leaveAbsence":"Permiso / ausencia","admin.noRequests":"No hay solicitudes recientes.","admin.office":"Oficina","admin.recentChecks":"Revisiones recientes"}
};

const preferencePacks: Record<Language, Messages> = {
  en:{"prefs.loading":"Loading your saved preferences…","prefs.savedAccount":"Saved to your FleetOS account","prefs.savedDevice":"Using this device's saved preferences","prefs.saving":"Saving…","prefs.syncFailed":"Saved on this device; account sync could not complete","prefs.reading":"Reading this page aloud.","prefs.readUnsupported":"Read aloud is not supported by this browser.","prefs.voiceUnsupported":"Voice input is not supported by this browser.","prefs.heard":"Heard","prefs.voiceFailed":"Voice input could not start. Check microphone permission and browser support.","prefs.listening":"Listening…","prefs.tryNow":"Try it now","prefs.speechTools":"Speech tools","prefs.readPage":"Read this page aloud","prefs.stopReading":"Stop reading","prefs.testVoice":"Test voice input","prefs.translationModel":"Translation model","prefs.originalTitle":"Original records stay original","prefs.originalDetail":"The selected language controls your interface and speech locale. Customer-entered evidence, notes and messages retain their original wording so the audit record is never changed."},
  pl:{"prefs.loading":"Ładowanie zapisanych preferencji…","prefs.savedAccount":"Zapisano na koncie FleetOS","prefs.savedDevice":"Używane są preferencje zapisane na tym urządzeniu","prefs.saving":"Zapisywanie…","prefs.syncFailed":"Zapisano na urządzeniu; synchronizacja konta nie powiodła się","prefs.reading":"Odczytywanie strony.","prefs.readUnsupported":"Ta przeglądarka nie obsługuje odczytu.","prefs.voiceUnsupported":"Ta przeglądarka nie obsługuje wprowadzania głosowego.","prefs.heard":"Usłyszano","prefs.voiceFailed":"Nie można uruchomić głosu. Sprawdź mikrofon i przeglądarkę.","prefs.listening":"Słuchanie…","prefs.tryNow":"Wypróbuj teraz","prefs.speechTools":"Narzędzia mowy","prefs.readPage":"Odczytaj tę stronę","prefs.stopReading":"Zatrzymaj odczyt","prefs.testVoice":"Testuj głos","prefs.translationModel":"Model tłumaczeń","prefs.originalTitle":"Oryginalne wpisy pozostają oryginalne","prefs.originalDetail":"Wybrany język steruje interfejsem i mową. Dowody, notatki i wiadomości użytkowników zachowują oryginalne brzmienie, aby zapis audytowy nie został zmieniony."},
  ro:{"prefs.loading":"Se încarcă preferințele salvate…","prefs.savedAccount":"Salvat în contul FleetOS","prefs.savedDevice":"Se folosesc preferințele salvate pe acest dispozitiv","prefs.saving":"Se salvează…","prefs.syncFailed":"Salvat pe dispozitiv; sincronizarea contului nu s-a finalizat","prefs.reading":"Pagina este citită cu voce tare.","prefs.readUnsupported":"Citirea vocală nu este acceptată de acest browser.","prefs.voiceUnsupported":"Introducerea vocală nu este acceptată.","prefs.heard":"Am auzit","prefs.voiceFailed":"Introducerea vocală nu a pornit. Verificați microfonul.","prefs.listening":"Ascultare…","prefs.tryNow":"Încearcă acum","prefs.speechTools":"Instrumente vocale","prefs.readPage":"Citește această pagină","prefs.stopReading":"Oprește citirea","prefs.testVoice":"Testează vocea","prefs.translationModel":"Model de traducere","prefs.originalTitle":"Înregistrările originale rămân originale","prefs.originalDetail":"Limba selectată controlează interfața și vocea. Dovezile, notele și mesajele introduse de utilizatori își păstrează formularea originală pentru a nu modifica auditul."},
  lt:{"prefs.loading":"Įkeliamos išsaugotos nuostatos…","prefs.savedAccount":"Išsaugota FleetOS paskyroje","prefs.savedDevice":"Naudojamos šiame įrenginyje išsaugotos nuostatos","prefs.saving":"Saugoma…","prefs.syncFailed":"Išsaugota įrenginyje; paskyros sinchronizuoti nepavyko","prefs.reading":"Puslapis skaitomas balsu.","prefs.readUnsupported":"Ši naršyklė nepalaiko skaitymo balsu.","prefs.voiceUnsupported":"Ši naršyklė nepalaiko balso įvesties.","prefs.heard":"Išgirsta","prefs.voiceFailed":"Nepavyko paleisti balso įvesties. Patikrinkite mikrofoną.","prefs.listening":"Klausoma…","prefs.tryNow":"Išbandykite dabar","prefs.speechTools":"Balso priemonės","prefs.readPage":"Perskaityti šį puslapį","prefs.stopReading":"Sustabdyti skaitymą","prefs.testVoice":"Išbandyti balso įvestį","prefs.translationModel":"Vertimo modelis","prefs.originalTitle":"Originalūs įrašai lieka originalūs","prefs.originalDetail":"Pasirinkta kalba valdo sąsają ir balsą. Naudotojų įrodymai, pastabos ir žinutės išlaiko originalų tekstą, todėl audito įrašas nekeičiamas."},
  bg:{"prefs.loading":"Зареждане на запазените предпочитания…","prefs.savedAccount":"Запазено в профила FleetOS","prefs.savedDevice":"Използват се предпочитанията от това устройство","prefs.saving":"Запазване…","prefs.syncFailed":"Запазено на устройството; синхронизирането не завърши","prefs.reading":"Страницата се прочита на глас.","prefs.readUnsupported":"Този браузър не поддържа четене на глас.","prefs.voiceUnsupported":"Този браузър не поддържа гласово въвеждане.","prefs.heard":"Чуто","prefs.voiceFailed":"Гласовото въвеждане не стартира. Проверете микрофона.","prefs.listening":"Слушане…","prefs.tryNow":"Опитайте сега","prefs.speechTools":"Гласови инструменти","prefs.readPage":"Прочети тази страница","prefs.stopReading":"Спри четенето","prefs.testVoice":"Тествай гласа","prefs.translationModel":"Модел за превод","prefs.originalTitle":"Оригиналните записи остават оригинални","prefs.originalDetail":"Избраният език управлява интерфейса и гласа. Въведените доказателства, бележки и съобщения запазват оригиналния текст, за да не се променя одитният запис."},
  uk:{"prefs.loading":"Завантаження збережених налаштувань…","prefs.savedAccount":"Збережено в обліковому записі FleetOS","prefs.savedDevice":"Використовуються налаштування цього пристрою","prefs.saving":"Збереження…","prefs.syncFailed":"Збережено на пристрої; синхронізацію не завершено","prefs.reading":"Сторінка читається вголос.","prefs.readUnsupported":"Цей браузер не підтримує читання вголос.","prefs.voiceUnsupported":"Цей браузер не підтримує голосове введення.","prefs.heard":"Почуто","prefs.voiceFailed":"Не вдалося запустити голосове введення. Перевірте мікрофон.","prefs.listening":"Слухаю…","prefs.tryNow":"Спробуйте зараз","prefs.speechTools":"Голосові інструменти","prefs.readPage":"Прочитати цю сторінку","prefs.stopReading":"Зупинити читання","prefs.testVoice":"Перевірити голос","prefs.translationModel":"Модель перекладу","prefs.originalTitle":"Оригінальні записи залишаються оригінальними","prefs.originalDetail":"Вибрана мова керує інтерфейсом і голосом. Докази, примітки та повідомлення користувачів зберігають оригінальний текст, щоб аудиторський запис не змінювався."},
  pt:{"prefs.loading":"A carregar as preferências guardadas…","prefs.savedAccount":"Guardado na conta FleetOS","prefs.savedDevice":"A usar as preferências deste dispositivo","prefs.saving":"A guardar…","prefs.syncFailed":"Guardado no dispositivo; não foi possível sincronizar a conta","prefs.reading":"A ler esta página em voz alta.","prefs.readUnsupported":"Este navegador não suporta leitura em voz alta.","prefs.voiceUnsupported":"Este navegador não suporta entrada de voz.","prefs.heard":"Ouvido","prefs.voiceFailed":"Não foi possível iniciar a voz. Verifique o microfone.","prefs.listening":"A ouvir…","prefs.tryNow":"Experimente agora","prefs.speechTools":"Ferramentas de voz","prefs.readPage":"Ler esta página","prefs.stopReading":"Parar leitura","prefs.testVoice":"Testar voz","prefs.translationModel":"Modelo de tradução","prefs.originalTitle":"Os registos originais permanecem originais","prefs.originalDetail":"O idioma selecionado controla a interface e a voz. Provas, notas e mensagens introduzidas pelos utilizadores mantêm o texto original para não alterar o registo de auditoria."},
  es:{"prefs.loading":"Cargando las preferencias guardadas…","prefs.savedAccount":"Guardado en la cuenta de FleetOS","prefs.savedDevice":"Usando las preferencias guardadas en este dispositivo","prefs.saving":"Guardando…","prefs.syncFailed":"Guardado en el dispositivo; no se pudo sincronizar la cuenta","prefs.reading":"Leyendo esta página en voz alta.","prefs.readUnsupported":"Este navegador no admite la lectura en voz alta.","prefs.voiceUnsupported":"Este navegador no admite la entrada de voz.","prefs.heard":"Oído","prefs.voiceFailed":"No se pudo iniciar la voz. Comprueba el permiso del micrófono.","prefs.listening":"Escuchando…","prefs.tryNow":"Pruébalo ahora","prefs.speechTools":"Herramientas de voz","prefs.readPage":"Leer esta página","prefs.stopReading":"Detener lectura","prefs.testVoice":"Probar entrada de voz","prefs.translationModel":"Modelo de traducción","prefs.originalTitle":"Los registros originales permanecen originales","prefs.originalDetail":"El idioma seleccionado controla la interfaz y la voz. Las pruebas, notas y mensajes introducidos por usuarios conservan su texto original para no alterar el registro de auditoría."}
};

const preferenceLabelPacks: Record<Language, Messages> = {
  en:{},
  pl:{"prefs.intro":"Te ustawienia należą do Twojego konta i działają w całym FleetOS od razu po zmianie.","prefs.translationReady":"Tekst interfejsu korzysta z pakietów językowych z angielskim jako językiem zapasowym. Wiadomości, dowody i zapisy audytowe zachowują oryginalne brzmienie.","prefs.largeText":"Duży tekst","prefs.largeControls":"Duże elementy sterujące","prefs.highContrast":"Wysoki kontrast","prefs.reducedMotion":"Ograniczony ruch","prefs.easyRead":"Łatwe czytanie","prefs.darkMode":"Tryb ciemny / nocny","prefs.readAloud":"Odczyt na głos","prefs.voiceInput":"Wprowadzanie głosowe"},
  ro:{"prefs.intro":"Aceste opțiuni aparțin contului tău și se aplică imediat în FleetOS.","prefs.translationReady":"Interfața folosește pachete lingvistice cu rezervă în engleză. Mesajele, dovezile și auditul își păstrează textul original.","prefs.largeText":"Text mare","prefs.largeControls":"Comenzi mari","prefs.highContrast":"Contrast ridicat","prefs.reducedMotion":"Mișcare redusă","prefs.easyRead":"Lectură ușoară","prefs.darkMode":"Mod întunecat / noapte","prefs.readAloud":"Citire cu voce tare","prefs.voiceInput":"Introducere vocală"},
  lt:{"prefs.intro":"Šie pasirinkimai priklauso jūsų paskyrai ir iškart taikomi visoje FleetOS.","prefs.translationReady":"Sąsaja naudoja kalbų paketus su anglų atsargine kalba. Žinutės, įrodymai ir audito įrašai išlaiko originalų tekstą.","prefs.largeText":"Didelis tekstas","prefs.largeControls":"Dideli valdikliai","prefs.highContrast":"Didelis kontrastas","prefs.reducedMotion":"Mažiau animacijos","prefs.easyRead":"Lengvas skaitymas","prefs.darkMode":"Tamsus / naktinis režimas","prefs.readAloud":"Skaitymas balsu","prefs.voiceInput":"Balso įvestis"},
  bg:{"prefs.intro":"Тези настройки принадлежат на профила ви и се прилагат веднага в FleetOS.","prefs.translationReady":"Интерфейсът използва езикови пакети с английски резервен текст. Съобщенията, доказателствата и одитът запазват оригиналния текст.","prefs.largeText":"Голям текст","prefs.largeControls":"Големи контроли","prefs.highContrast":"Висок контраст","prefs.reducedMotion":"Намалено движение","prefs.easyRead":"Лесно четене","prefs.darkMode":"Тъмен / нощен режим","prefs.readAloud":"Прочитане на глас","prefs.voiceInput":"Гласово въвеждане"},
  uk:{"prefs.intro":"Ці налаштування належать вашому обліковому запису й одразу діють у FleetOS.","prefs.translationReady":"Інтерфейс використовує мовні пакети з англійським резервним текстом. Повідомлення, докази та аудит зберігають оригінальний текст.","prefs.largeText":"Великий текст","prefs.largeControls":"Великі елементи керування","prefs.highContrast":"Високий контраст","prefs.reducedMotion":"Менше анімації","prefs.easyRead":"Легке читання","prefs.darkMode":"Темний / нічний режим","prefs.readAloud":"Читання вголос","prefs.voiceInput":"Голосове введення"},
  pt:{"prefs.intro":"Estas escolhas pertencem à sua conta e aplicam-se imediatamente em todo o FleetOS.","prefs.translationReady":"A interface usa pacotes de idiomas com inglês como alternativa. Mensagens, provas e auditoria mantêm o texto original.","prefs.largeText":"Texto grande","prefs.largeControls":"Controlos grandes","prefs.highContrast":"Alto contraste","prefs.reducedMotion":"Movimento reduzido","prefs.easyRead":"Leitura fácil","prefs.darkMode":"Modo escuro / noturno","prefs.readAloud":"Leitura em voz alta","prefs.voiceInput":"Entrada de voz"},
  es:{"prefs.intro":"Estas opciones pertenecen a tu cuenta y se aplican inmediatamente en todo FleetOS.","prefs.translationReady":"La interfaz usa paquetes de idiomas con inglés como alternativa. Los mensajes, pruebas y auditorías conservan el texto original.","prefs.largeText":"Texto grande","prefs.largeControls":"Controles grandes","prefs.highContrast":"Alto contraste","prefs.reducedMotion":"Movimiento reducido","prefs.easyRead":"Lectura fácil","prefs.darkMode":"Modo oscuro / nocturno","prefs.readAloud":"Lectura en voz alta","prefs.voiceInput":"Entrada de voz"}
};

type I18nValue = { language: Language; t: (key: string) => string; locale: string };
const I18nContext = createContext<I18nValue>({ language:"en", t:key=>en[key] ?? key, locale:"en-GB" });
const locales: Record<Language,string> = { en:"en-GB",pl:"pl-PL",ro:"ro-RO",lt:"lt-LT",bg:"bg-BG",uk:"uk-UA",pt:"pt-PT",es:"es-ES" };

export function I18nProvider({ children }:{ children:ReactNode }) {
  const [language,setLanguage]=useState<Language>(()=>loadLocalAccessibilityPreferences().language);
  useEffect(()=>{const update=(event:Event)=>setLanguage(((event as CustomEvent<AccessibilityPreferences>).detail ?? loadLocalAccessibilityPreferences()).language);window.addEventListener("fleetos:preferences",update);window.addEventListener("storage",update);return()=>{window.removeEventListener("fleetos:preferences",update);window.removeEventListener("storage",update);};},[]);
  const value=useMemo<I18nValue>(()=>({language,locale:locales[language],t:(key)=>preferenceLabelPacks[language][key] ?? preferencePacks[language][key] ?? adminPacks[language][key] ?? packs[language][key] ?? preferenceLabelPacks.en[key] ?? preferencePacks.en[key] ?? adminPacks.en[key] ?? en[key] ?? key}),[language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export const useI18n=()=>useContext(I18nContext);


