import { FormEvent, useEffect, useState } from "react";
import { api } from "../../lib/api";

type Listing={id:string;companyId:string;companyName:string;category:string;title:string;description:string|null;location:string|null;pricePence:number|null;status:string;createdAt:string};
type Inquiry={id:string;listingId:string;listingTitle:string;sellerCompanyId:string;sellerCompanyName:string;fromCompanyId:string;fromCompanyName:string;message:string;status:string;direction:"INCOMING"|"OUTGOING";createdAt:string};

export function MarketplacePage(){
  const [tab,setTab]=useState<"network"|"mine"|"inquiries">("network");
  const [listings,setListings]=useState<Listing[]>([]); const [mine,setMine]=useState<Listing[]>([]); const [inquiries,setInquiries]=useState<Inquiry[]>([]);
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({category:"HELP",title:"",description:"",location:"",price:""});
  const [enquire,setEnquire]=useState<Listing|null>(null); const [message,setMessage]=useState("");
  async function load(){try{const [a,b,c]=await Promise.all([api<Listing[]>("/marketplace/listings"),api<Listing[]>("/marketplace/mine"),api<Inquiry[]>("/marketplace/inquiries")]);setListings(a);setMine(b);setInquiries(c);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load marketplace.");}}
  useEffect(()=>{void load();},[]);
  async function create(e:FormEvent){e.preventDefault();if(!form.title.trim())return;setBusy(true);setError("");try{await api("/marketplace/listings",{method:"POST",body:JSON.stringify({category:form.category,title:form.title.trim(),description:form.description.trim()||undefined,location:form.location.trim()||undefined,pricePence:form.price?Math.round(Number(form.price)*100):undefined})});setForm({category:"HELP",title:"",description:"",location:"",price:""});await load();setTab("mine");}catch(e){setError(e instanceof Error?e.message:"Could not create listing.");}finally{setBusy(false);}}
  async function sendInquiry(e:FormEvent){e.preventDefault();if(!enquire||!message.trim())return;setBusy(true);setError("");try{await api(`/marketplace/listings/${enquire.id}/inquiries`,{method:"POST",body:JSON.stringify({message:message.trim()})});setEnquire(null);setMessage("");await load();setTab("inquiries");}catch(e){setError(e instanceof Error?e.message:"Could not send enquiry.");}finally{setBusy(false);}}
  async function setListingStatus(id:string,status:string){setBusy(true);try{await api(`/marketplace/listings/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load();}catch(e){setError(e instanceof Error?e.message:"Could not update listing.");}finally{setBusy(false);}}
  async function closeInquiry(id:string){setBusy(true);try{await api(`/marketplace/inquiries/${id}/close`,{method:"PATCH"});await load();}catch(e){setError(e instanceof Error?e.message:"Could not close enquiry.");}finally{setBusy(false);}}
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">FleetOS network</p><h1>Marketplace & Help Network</h1><p className="subtle">Share spare capacity, parts, equipment or requests with other FleetOS companies without exposing private fleet data.</p></div></div>
    {error&&<div className="panel" style={{padding:14,marginBottom:16,borderColor:"#dc2626",color:"#991b1b"}}>{error}</div>}
    <div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap"}}>{[["network","Network"],["mine","My company listings"],["inquiries","Enquiries"]].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={tab===id?"primary-button":"secondary-button"}>{label}</button>)}</div>
    {tab==="network"&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14}}>{listings.length===0?<div className="panel" style={{padding:20}}>No active network listings yet.</div>:listings.map(x=><article key={x.id} className="panel" style={{padding:16}}><div className="subtle">{x.category.replaceAll("_"," ")} · {x.companyName}</div><h2>{x.title}</h2>{x.description&&<p>{x.description}</p>}<div className="subtle">{x.location||"Location not set"}{x.pricePence!=null?` · £${(x.pricePence/100).toFixed(2)}`:""}</div><button className="primary-button" style={{marginTop:12}} onClick={()=>{setEnquire(x);setMessage("");}}>Enquire</button></article>)}</div>{enquire&&<form className="panel" onSubmit={sendInquiry} style={{padding:18,marginTop:16}}><h2>Enquire about {enquire.title}</h2><p className="subtle">Your message goes only to the listing company and stays separate from internal company chat.</p><textarea required maxLength={3000} rows={4} value={message} onChange={e=>setMessage(e.target.value)} style={{width:"100%"}}/><div style={{display:"flex",gap:8,marginTop:10}}><button className="primary-button" disabled={busy}>Send enquiry</button><button type="button" onClick={()=>setEnquire(null)}>Cancel</button></div></form>}</>}
    {tab==="mine"&&<><form className="panel" onSubmit={create} style={{padding:18,marginBottom:16}}><h2>Publish a listing</h2><div className="form-grid"><label>Category<select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}><option>HELP</option><option>PARTS</option><option>EQUIPMENT</option><option>VEHICLE</option><option>CAPACITY</option><option>SERVICE</option><option>OTHER</option></select></label><label>Title<input required maxLength={160} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>Location<input maxLength={120} value={form.location} onChange={e=>setForm(v=>({...v,location:e.target.value}))}/></label><label>Price £ (optional)<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm(v=>({...v,price:e.target.value}))}/></label></div><label style={{display:"block",marginTop:10}}>Description<textarea rows={3} maxLength={3000} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label><button className="primary-button" disabled={busy} style={{marginTop:10}}>Publish</button></form><div style={{display:"grid",gap:10}}>{mine.map(x=><article key={x.id} className="panel" style={{padding:14,display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{x.title}</strong><div className="subtle">{x.category} · {x.status}</div></div><div>{x.status==="ACTIVE"?<button disabled={busy} onClick={()=>void setListingStatus(x.id,"CLOSED")}>Close</button>:<button disabled={busy} onClick={()=>void setListingStatus(x.id,"ACTIVE")}>Reopen</button>}</div></article>)}</div></>}
    {tab==="inquiries"&&<div style={{display:"grid",gap:10}}>{inquiries.length===0?<div className="panel" style={{padding:20}}>No marketplace enquiries yet.</div>:inquiries.map(x=><article key={x.id} className="panel" style={{padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong>{x.listingTitle}</strong><span className="presence">{x.direction}</span></div><div className="subtle">Seller: {x.sellerCompanyName} · Buyer: {x.fromCompanyName} · {x.status}</div><p>{x.message}</p>{x.status==="OPEN"&&<button disabled={busy} onClick={()=>void closeInquiry(x.id)}>Close enquiry</button>}</article>)}</div>}
  </section>;
}
